const $=s=>document.querySelector(s);let settings;const foodNames={leaf:'菜叶',worm:'面包虫',cookie:'小饼干',paste:'营养糊糊'};let feedPortion=1,defaultClickEffectDataUrl='../assets/click-hamster-default.jpg';
async function prepareDefaultClickEffect(){
  try{const image=new Image();image.src='../assets/click-hamster-default.jpg';await image.decode();const canvas=document.createElement('canvas'),size=220,scale=Math.min(size/image.naturalWidth,size/image.naturalHeight);canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));const context=canvas.getContext('2d',{willReadFrequently:true});context.drawImage(image,0,0,canvas.width,canvas.height);const pixels=context.getImageData(0,0,canvas.width,canvas.height),data=pixels.data;for(let i=0;i<data.length;i+=4){const min=Math.min(data[i],data[i+1],data[i+2]),max=Math.max(data[i],data[i+1],data[i+2]);if(max-min<34&&min>188){const alpha=Math.max(0,Math.min(1,(232-min)/44));data[i+3]=Math.round(data[i+3]*alpha)}}context.putImageData(pixels,0,0);defaultClickEffectDataUrl=canvas.toDataURL('image/png')}catch{}
}
prepareDefaultClickEffect();
function initVisualEffects(){
  const main=$('main');
  if(!main||$('.background-motion-layer'))return;
  const layer=document.createElement('div');
  layer.className='background-motion-layer';
  layer.setAttribute('aria-hidden','true');
  layer.innerHTML='<i></i><i></i><i></i><i></i><i></i><span></span><span></span><span></span><span></span><span></span><span></span>';
  main.prepend(layer);
  const reduce=window.matchMedia('(prefers-reduced-motion: reduce)');
  const footprintTones=['violet','green','cyan','blue','yellow'];
  let lastX=-100,lastY=-100,lastTime=0,step=0;
  document.addEventListener('pointermove',e=>{
    if(settings?.pawTrailEnabled===false||reduce.matches||document.hidden||(e.pointerType&&e.pointerType!=='mouse'))return;
    const now=performance.now(),dx=e.clientX-lastX,dy=e.clientY-lastY,distance=Math.hypot(dx,dy);
    if(distance<27||now-lastTime<52)return;
    const angle=Math.atan2(dy,dx)*180/Math.PI+90,side=step%2===0?-5:5,length=Math.max(distance,1);
    const paw=document.createElement('span');
    paw.className=`paw-trail paw-${footprintTones[step%footprintTones.length]}`;
    paw.setAttribute('aria-hidden','true');
    paw.style.left=`${e.clientX+(side*-dy/length)-6}px`;
    paw.style.top=`${e.clientY+(side*dx/length)-7}px`;
    paw.style.rotate=`${angle}deg`;
    document.body.appendChild(paw);
    step++;lastX=e.clientX;lastY=e.clientY;lastTime=now;
    const paws=document.querySelectorAll('.paw-trail');if(paws.length>24)paws[0].remove();
    paw.addEventListener('animationend',()=>paw.remove(),{once:true});
    setTimeout(()=>paw.remove(),1400);
  },{passive:true});
  document.addEventListener('pointerdown',e=>{
    if(e.button!==0||settings?.clickEffectEnabled===false)return;
    const burst=document.createElement('span');
    burst.className='click-hamster-burst';
    burst.setAttribute('aria-hidden','true');
    burst.style.left=`${e.clientX-24}px`;burst.style.top=`${e.clientY-24}px`;
    const image=document.createElement('img');
    image.alt='';
    image.src=settings?.clickEffectDataUrl||defaultClickEffectDataUrl;
    burst.appendChild(image);
    document.body.appendChild(burst);
    burst.addEventListener('animationend',()=>burst.remove(),{once:true});
    setTimeout(()=>burst.remove(),1100);
  },{passive:true});
}
initVisualEffects();
const unifiedSettingsPanel=$('#effectSettings');if(unifiedSettingsPanel&&$('.grid')){unifiedSettingsPanel.className='card panel-section wide unified-settings unified-settings-page';unifiedSettingsPanel.dataset.section='settings';unifiedSettingsPanel.removeAttribute('aria-hidden');$('.grid').prepend(unifiedSettingsPanel)}
const unifiedProfilePanel=$('#mouseProfilePopover');if(unifiedProfilePanel&&$('.grid')){unifiedProfilePanel.className='card panel-section wide mouse-profile-page';unifiedProfilePanel.dataset.section='profile';unifiedProfilePanel.removeAttribute('aria-hidden');$('.grid').prepend(unifiedProfilePanel)}
const sidebarProfile=document.querySelector('aside small');if(sidebarProfile){sidebarProfile.className='mouse-id-card';sidebarProfile.innerHTML='<span class="mouse-id-title"><i>🐹</i>鼠鼠身份卡</span><span class="mouse-id-grid"><span><b>🎂 出生日期</b><em>2024.06.09</em></span><span><b>⚖️ 体重</b><em>六十多克</em></span><span><b>♂ 性别</b><em>小男鼠</em></span><span><b>🌙 作息</b><em>夜间活跃</em></span></span><span class="mouse-id-foot">♥ 你的小仓鼠桌面伙伴</span>'}
const hamsterActions=[
  {id:'idle-a',icon:'🐹',name:'安静坐着',desc:'正面静置，轻轻活动小手'},
  {id:'idle-b',icon:'👀',name:'侧头观察',desc:'换一个角度看看桌面'},
  {id:'groom-a',icon:'🧼',name:'低头理毛',desc:'低头整理自己的毛发'},
  {id:'groom-b',icon:'🌀',name:'转身整理',desc:'转身后继续清洁身体'},
  {id:'eat-a',icon:'🥬',name:'认真吃菜',desc:'抱着菜叶慢慢咀嚼'},
  {id:'eat-b',icon:'😋',name:'继续加餐',desc:'另一段真实吃菜动作'}
];
function escapeHtml(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
function render(){if(!settings)return;['keyboardReaction','idleWheel','randomTalk','soundEnabled'].forEach(k=>$('#'+k).checked=!!settings[k]);if($('#pawTrailEnabled'))$('#pawTrailEnabled').checked=settings.pawTrailEnabled!==false;$('#idleDelay').value=settings.idleDelay;$('#delayText').textContent=settings.idleDelay;$('#mood').textContent=settings.mood+'%';$('#hunger').textContent=settings.hunger+'%';$('#moodBar').style.width=settings.mood+'%';$('#hungerBar').style.width=settings.hunger+'%';document.querySelectorAll('[data-outfit]').forEach(b=>b.classList.toggle('active',b.dataset.outfit===settings.outfit));document.querySelectorAll('[data-form]').forEach(b=>b.classList.toggle('active',b.dataset.form===(settings.petForm||'3d')));$('#lineList').innerHTML=(settings.customLines||[]).map((x,i)=>`<div class="line"><span>${escapeHtml(x)}</span><button data-remove="${i}">删除</button></div>`).join('')||'<p class="hint">还没有自定义台词</p>';if($('#aiBaseUrl')&&document.activeElement!==$('#aiBaseUrl'))$('#aiBaseUrl').value=settings.aiBaseUrl||'https://api.openai.com/v1';if($('#aiModel')&&document.activeElement!==$('#aiModel'))$('#aiModel').value=settings.aiModel||'gpt-4o-mini';if($('#aiApiKey')&&document.activeElement!==$('#aiApiKey'))$('#aiApiKey').value=settings.aiApiKey||'';const mode=settings.chatMode||'local';document.querySelectorAll('[data-chat-mode]').forEach(b=>b.classList.toggle('active',b.dataset.chatMode===mode));if($('#aiSettings'))$('#aiSettings').classList.toggle('enabled',mode==='ai');if($('#keyNote'))$('#keyNote').textContent=mode==='ai'?'🔒 AI 模式使用你自己的接口额度，Key 只保存在这台电脑。':'🏠 当前为免费本地模式，不联网，也不会产生任何 API 费用。';renderChat();renderActionLibrary()}
function renderChat(){if(!$('#chatMessages')||!settings)return;const history=settings.chatHistory||[],mode=settings.chatMode||'local',emptyHint=mode==='local'?'现在就可以免费和鼠鼠说话啦。':'填写并保存接口设置后，就可以使用 AI 聊天。';$('#chatMessages').innerHTML=history.length?history.map(x=>`<div class="chat-message ${x.role==='user'?'user':'mouse'}"><b>${x.role==='user'?'你':'鼠鼠'}</b><p>${escapeHtml(x.content)}</p></div>`).join(''):`<p class="hint">${emptyHint}</p>`;$('#chatMessages').scrollTop=$('#chatMessages').scrollHeight}
async function save(p){settings=await window.petAPI.saveSettings(p);render();syncUnifiedSettings();applyLanguage();return settings}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const panelMeta={home:['鼠鼠功能主页','所有陪伴功能，都藏在这只小仓鼠里'],chat:['和鼠鼠聊天','说说今天的心情，鼠鼠会认真听'],actions:['鼠鼠动作库','管理和预览鼠鼠的真实动态'],diary:['小鼠日记','翻看你们每天共同留下的记录'],behavior:['行为与装扮','调整鼠鼠的习惯、形态和装扮'],dialogue:['对话管理','写下只属于你和鼠鼠的台词'],feed:['喂食互动','准备喜欢的食物，看鼠鼠慢慢吃掉'],settings:['应用设置','集中管理语言、鼠标特效、行为与形态'],profile:['鼠鼠基本信息','查看鼠鼠的身份、年龄与生活习惯'],feedback:['问题反馈','告诉我们哪里需要改进']};
const panelMetaTranslated={en:{home:['Hamster home','Every companion feature lives around Hamster'],chat:['Chat with Hamster','Share your day — Hamster is listening'],actions:['Action library','Manage and preview Hamster’s real motions'],diary:['Hamster diary','Revisit the days you spent together'],behavior:['Behavior & outfits','Adjust form, habits and outfits'],dialogue:['Dialogue manager','Write lines that belong to you and Hamster'],feed:['Feeding','Prepare a favorite snack and watch Hamster eat'],settings:['App settings','Manage language, cursor effects, behavior and form'],profile:['About Hamster','View Hamster’s identity, age and daily habits'],feedback:['Feedback','Tell us what we can improve']},es:{home:['Inicio de Hámster','Todas las funciones viven alrededor de Hámster'],chat:['Hablar con Hámster','Cuéntale tu día; Hámster te escucha'],actions:['Biblioteca de acciones','Gestiona los movimientos reales de Hámster'],diary:['Diario de Hámster','Recuerda los días que pasaron juntos'],behavior:['Conducta y ropa','Ajusta forma, hábitos y accesorios'],dialogue:['Gestión de diálogos','Escribe frases para Hámster'],feed:['Alimentación','Prepara su comida favorita'],settings:['Ajustes de la aplicación','Gestiona idioma, efectos, conducta y forma'],profile:['Datos de Hámster','Consulta su identidad, edad y hábitos diarios'],feedback:['Comentarios','Dinos qué podemos mejorar']}};
const uiTranslations={zh:{settings:'设置',title:'今天想和鼠鼠做什么？',sub:'轻轻点它的耳朵、脸颊、小爪或肚子。',settingsTitle:'应用设置',settingsSub:'所有偏好都集中在这里',switches:['鼠标移动特效','鼠标点击特效','敲键盘时同步打字','闲置时跑跑轮','随机说话','真实叫声'],language:'界面语言',form:'鼠鼠形态',delay:'闲置活动延时 ',upload:'上传自定义点击特效',restore:'恢复默认点击特效',show:'叫鼠鼠出来 ↗',back:'← 返回功能主页',features:['和鼠鼠聊天','对话管理','鼠鼠动作库','行为与装扮','喂食互动','小鼠日记'],parts:['左耳','右耳','脸颊','左爪','肚子','右爪'],stage:['鼠鼠功能主页','六个区域，六种陪伴'],open:'打开设置'},en:{settings:'Settings',title:'What would you like to do with Hamster?',sub:'Move over the ears, cheek, paws or belly.',settingsTitle:'App settings',settingsSub:'All preferences are collected here',switches:['Pointer move effect','Click effect','React while typing','Run wheel when idle','Random speech','Real sounds'],language:'Interface language',form:'Hamster form',delay:'Idle activity delay ',upload:'Upload custom click effect',restore:'Restore default click effect',show:'Show Hamster ↗',back:'← Back to Hamster home',features:['Chat with Hamster','Dialogue manager','Action library','Behavior & outfits','Feeding','Hamster diary'],parts:['Left ear','Right ear','Cheek','Left paw','Belly','Right paw'],stage:['Hamster home','Six areas, six ways to stay together'],open:'Open settings'},es:{settings:'Ajustes',title:'¿Qué quieres hacer con Hámster?',sub:'Pasa por sus orejas, mejilla, patas o barriga.',settingsTitle:'Ajustes de la aplicación',settingsSub:'Todas las preferencias están aquí',switches:['Efecto al mover el cursor','Efecto de clic','Reaccionar al escribir','Rueda al estar inactivo','Hablar al azar','Sonidos reales'],language:'Idioma de la interfaz',form:'Forma de Hámster',delay:'Retraso de actividad ',upload:'Subir efecto de clic personalizado',restore:'Restaurar efecto predeterminado',show:'Mostrar a Hámster ↗',back:'← Volver al inicio',features:['Hablar con Hámster','Gestión de diálogos','Biblioteca de acciones','Conducta y ropa','Alimentación','Diario de Hámster'],parts:['Oreja izquierda','Oreja derecha','Mejilla','Pata izquierda','Barriga','Pata derecha'],stage:['Inicio de Hámster','Seis zonas, seis formas de acompañar'],open:'Abrir ajustes'}};
function syncUnifiedSettings(){if(!settings)return;['keyboardReaction','idleWheel','randomTalk','soundEnabled'].forEach(k=>{if($('#'+k))$('#'+k).checked=!!settings[k]});if($('#pawTrailEnabled'))$('#pawTrailEnabled').checked=settings.pawTrailEnabled!==false;if($('#clickEffectEnabled'))$('#clickEffectEnabled').checked=settings.clickEffectEnabled!==false;if($('#interfaceLanguage'))$('#interfaceLanguage').value=settings.interfaceLanguage||'zh';if($('#settingsPetForm'))$('#settingsPetForm').value=settings.petForm||'3d';if($('#idleDelay'))$('#idleDelay').value=settings.idleDelay;if($('#delayText'))$('#delayText').textContent=settings.idleDelay}
function applyLanguage(){if(!settings)return;const lang=settings.interfaceLanguage||'zh',t=uiTranslations[lang]||uiTranslations.zh;document.documentElement.lang=lang==='zh'?'zh-CN':lang;$('#effectSettingsButton').textContent=t.settings;$('.feature-intro h3').textContent=t.title;$('.feature-intro p').textContent=t.sub;$('.settings-title b').textContent=t.settingsTitle;$('.settings-title span').textContent=t.settingsSub;document.querySelectorAll('.settings-grid .effect-switch>span').forEach((node,i)=>node.textContent=t.switches[i]);const rows=document.querySelectorAll('.settings-row label');if(rows[0])rows[0].childNodes[0].nodeValue=t.language;if(rows[1])rows[1].childNodes[0].nodeValue=t.form;const delay=$('.settings-delay');if(delay)delay.childNodes[0].nodeValue=t.delay;$('#chooseClickEffect').textContent=t.upload;$('#restoreClickEffect').textContent=t.restore;$('#togglePetTop').textContent=t.show;$('#backHome').textContent=t.back;document.querySelectorAll('.photo-map .hamster-tile').forEach((node,i)=>{node.querySelector('b').textContent=t.features[i];node.querySelector('.feature-index').textContent=t.parts[i]});const stage=$('.stage-note');stage.querySelector('b').textContent=t.stage[0];stage.querySelector('span').textContent=t.stage[1];if($('#openUnifiedSettings'))$('#openUnifiedSettings').textContent=t.open;const current=document.body.dataset.currentPanel||'home',meta=(panelMetaTranslated[lang]?.[current]||panelMeta[current]||panelMeta.home);$('#pageTitle').textContent=meta[0];$('#pageSubtitle').textContent=meta[1]}
function setPanel(name){document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.panel===name));document.querySelectorAll('.panel-section').forEach(s=>s.classList.toggle('active',s.dataset.section===name));document.body.dataset.currentPanel=name;const lang=settings?.interfaceLanguage||'zh',meta=(panelMetaTranslated[lang]?.[name]||panelMeta[name]||panelMeta.home);if($('#pageTitle'))$('#pageTitle').textContent=meta[0];if($('#pageSubtitle'))$('#pageSubtitle').textContent=meta[1];if($('#backHome'))$('#backHome').classList.toggle('show',name!=='home');document.querySelector('main')?.scrollTo({top:0,behavior:'smooth'})}
function allActions(){return [...hamsterActions.map(a=>({...a,name:settings?.actionNames?.[a.id]||a.name})),...(settings?.customActions||[]).map(a=>({...a,icon:'✨',desc:'你添加的自定义透明动作',custom:true}))]}
function renderActionLibrary(){const list=allActions(),lang=settings?.interfaceLanguage||'zh',dict=exactUiText?.[lang]||{};$('#actionCount').textContent=list.length;$('#actionGrid').innerHTML=list.map((a,i)=>{const customName=settings?.actionNames?.[a.id]||a.custom,shownName=lang==='zh'||customName?a.name:(dict[a.name]||a.name),shownDesc=lang==='zh'?a.desc:(dict[a.desc]||a.desc);return `<article><div class="action-info"><i>${a.icon}</i><b>${i+1}. ${escapeHtml(shownName)}</b><p>${escapeHtml(shownDesc)}</p><input class="action-name-input" maxlength="24" value="${escapeHtml(shownName)}" aria-label="修改动作名称"></div><div class="action-buttons"><button data-preview-action="${a.id}">▶ 预览</button><button class="rename-action" data-save-action-name="${a.id}">保存名称</button>${a.custom?`<button class="delete-action" data-delete-action="${a.id}">删除</button>`:''}</div></article>`}).join('')}
async function renderDiaryArchive(selected){const list=await window.petAPI.getDiaryList();$('#diaryArchive').innerHTML=list.length?list.map(e=>`<button data-diary-date="${e.date}" class="${e.date===selected?'active':''}"><b>${e.date===today()?'今天':e.date}</b><span>${escapeHtml(e.body.slice(0,25))}…</span></button>`).join(''):'<p class="hint">今天将是第一篇日记</p>'}
async function showDiary(date){const e=await window.petAPI.getDiary(date);$('#diaryDate').value=e.date;$('#diaryPaper').innerHTML=`<div class="diary-title">${escapeHtml(e.title)}</div><p>${escapeHtml(e.body)}</p><div class="diary-stats"><span>💗 互动 ${e.stats.interactions}</span><span>🥬 投喂 ${e.stats.feeds}</span><span>🎡 跑轮 ${e.stats.wheel}</span></div><div class="paw">🐾 鼠鼠</div>`;await renderDiaryArchive(e.date)}
function renderAge(){const now=new Date(),born=new Date(2024,5,9),days=Math.floor((now-born)/86400000);let years=now.getFullYear()-born.getFullYear(),months=now.getMonth()-born.getMonth();if(now.getDate()<born.getDate())months--;if(months<0){years--;months+=12}$('#ageText').textContent=`🎂 ${years}岁${months}个月 · 来到世界${days}天`;if($('#profileAge'))$('#profileAge').textContent=`${years}岁${months}个月`;let birthday=new Date(now.getFullYear(),5,9);if(birthday<new Date(now.getFullYear(),now.getMonth(),now.getDate()))birthday=new Date(now.getFullYear()+1,5,9);const left=Math.ceil((birthday-new Date(now.getFullYear(),now.getMonth(),now.getDate()))/86400000);$('#birthdayText').textContent=left===0?'🎉 今天生日！':`🎈 距生日 ${left} 天`}
function renderHeroGreeting(){const hour=new Date().getHours();$('#heroGreeting').textContent=hour<6?'夜深了，鼠鼠陪你一会儿':hour<11?'早上好，今天也一起加油':hour<14?'到午休时间啦，先喘口气':hour<18?'下午好，鼠鼠一直在这里':'晚上好，到鼠鼠活跃的时间啦'}
async function refreshHome(){if(!settings)return;const o=await window.petAPI.getOverview();$('#todayInteractions').textContent=o.day.interactions;$('#todayFeeds').textContent=o.day.feeds;$('#todayWheel').textContent=o.day.wheel;$('#todayMinutes').textContent=o.minutes;const points=o.totals.interactions*2+o.totals.feeds*5+o.totals.wheel*3,levels=[['初次见面',0,30],['熟悉的气味',30,100],['最信任的主人',100,250],['永远的小伙伴',250,500]],index=levels.findIndex((x,i)=>points<x[2]||i===levels.length-1),level=levels[index];$('#affinityLevel').textContent=`Lv.${index+1} ${level[0]}`;$('#affinityBar').style.width=`${Math.min(100,(points-level[1])/(level[2]-level[1])*100)}%`;$('#affinityText').textContent=index===levels.length-1?'鼠鼠最信任的人就是你。':`亲密值 ${points} · 距离下一等级还差 ${Math.max(0,level[2]-points)}`;$('#diaryPreview').textContent=o.diary.body;$('#previewStats').innerHTML=`<span>💗 ${o.day.interactions} 次互动</span><span>🥬 ${o.day.feeds} 次投喂</span><span>🎡 ${o.day.wheel} 次跑轮</span>`;$('#statusText').textContent=settings.mood>=85&&settings.hunger>=70?'心情很好，肚子也很满足':settings.hunger<50?'肚子有一点饿了':settings.mood<60?'今天想让你多陪陪':'正在安静地陪着你'}
window.petAPI.getSettings().then(s=>{settings=s;render();syncUnifiedSettings();applyLanguage();refreshHome()});window.petAPI.onSettings(s=>{settings=s;render();syncUnifiedSettings();applyLanguage()});
window.petAPI.onStatus(status=>{const lang=settings?.interfaceLanguage||'zh',shown=lang==='zh'?status:(exactUiText[lang]?.[status]||status.replaceAll('鼠鼠',lang==='en'?'Hamster':'Hámster'));$('#liveStatus').textContent=shown;$('#homeStatus').textContent=shown;$('#statusFace').textContent=status.includes('睡')?'😴':status.includes('跑')?'🎡':status.includes('开心')?'🥰':'🐹'});
['keyboardReaction','idleWheel','randomTalk','soundEnabled'].forEach(k=>$('#'+k).onchange=e=>save({[k]:e.target.checked}));$('#idleDelay').oninput=e=>{$('#delayText').textContent=e.target.value};$('#idleDelay').onchange=e=>save({idleDelay:Number(e.target.value)});
async function feedMouse(food){settings=await window.petAPI.feed(food,feedPortion);$('#feedResult').textContent=food==='leaf'?'鼠鼠把菜叶抱在手里，正在一口一口慢慢吃。':`鼠鼠接过${foodNames[food]}，开始认真享用啦！`;render();await refreshHome();await refreshFeedSummary()}
async function refreshFeedSummary(){if(!settings||!$('#feedCounts'))return;const o=await window.petAPI.getOverview(),counts=o.day.feedDetails||{},text=Object.entries(counts).filter(([,n])=>n).map(([k,n])=>`${foodNames[k]||k} ${n}口`).join(' · ');$('#feedCounts').textContent=text||'还没有投喂，鼠鼠正在等你～';$('#lastFood').textContent=foodNames[settings.lastFood]||'还没有'}
document.querySelectorAll('[data-outfit]').forEach(b=>b.onclick=()=>save({outfit:b.dataset.outfit}));document.querySelectorAll('[data-food]').forEach(b=>b.onclick=()=>feedMouse(b.dataset.food));
document.querySelectorAll('[data-portion]').forEach(b=>b.onclick=()=>{feedPortion=Number(b.dataset.portion);document.querySelectorAll('[data-portion]').forEach(x=>x.classList.toggle('active',x===b))});
$('#randomFood').onclick=()=>{const foods=['leaf','worm','cookie','paste'];feedMouse(foods[Math.floor(Math.random()*foods.length)])};
const petFormMessage=form=>form==='3d'?'已切换为 3D 模型，可按住鼠鼠旋转。':form==='ai-drama'?'已切换为 AI 漫剧形态，支持呼吸、蹦跳、睡觉、侧躺、开心和爬行。':'已切换为真实动态。';
const nextPetForm=form=>({'3d':'ai-drama','ai-drama':'real','real':'3d'}[form]||'3d');
document.querySelectorAll('[data-form]').forEach(b=>b.onclick=async()=>{await save({petForm:b.dataset.form});$('#formHint').textContent=petFormMessage(b.dataset.form)});
$('#addLine').onclick=()=>{const v=$('#newLine').value.trim();if(!v)return;save({customLines:[...(settings.customLines||[]),v]});$('#newLine').value=''};$('#lineList').onclick=e=>{if(e.target.dataset.remove!==undefined){const a=[...settings.customLines];a.splice(Number(e.target.dataset.remove),1);save({customLines:a})}};$('#togglePet').onclick=()=>window.petAPI.togglePet();
$('#saveAI').onclick=async()=>{await save({aiBaseUrl:$('#aiBaseUrl').value.trim(),aiModel:$('#aiModel').value.trim(),aiApiKey:$('#aiApiKey').value.trim()});$('#chatStatus').textContent='AI 对话设置已保存在这台电脑。'};
document.querySelectorAll('[data-chat-mode]').forEach(button=>button.onclick=async()=>{await save({chatMode:button.dataset.chatMode});$('#chatStatus').textContent=button.dataset.chatMode==='local'?'已切换到免费本地聊天，不会产生费用。':'已切换到 AI 智能聊天，请确认接口设置可用。'});
async function sendChat(){const message=$('#chatInput').value.trim();if(!message||$('#sendChat').disabled)return;$('#chatInput').value='';$('#sendChat').disabled=true;$('#chatStatus').textContent=(settings.chatMode||'local')==='local'?'鼠鼠正在认真理解你说的话……':'鼠鼠正在通过 AI 思考怎么回答……';const pending={role:'user',content:message};settings={...settings,chatHistory:[...(settings.chatHistory||[]),pending]};renderChat();try{const result=await window.petAPI.chat(message);if(result?.ok){settings={...settings,chatHistory:result.history};renderChat();$('#chatStatus').textContent=result.mode==='local'?'鼠鼠已用免费本地模式回答。':'鼠鼠已经通过 AI 回答你啦。'}else{settings={...settings,chatHistory:(settings.chatHistory||[]).slice(0,-1)};renderChat();$('#chatStatus').textContent=`没有收到回复：${result?.error||'本地聊天暂时没有响应'}`}}catch(error){settings={...settings,chatHistory:(settings.chatHistory||[]).slice(0,-1)};renderChat();$('#chatStatus').textContent=`聊天连接已恢复，请再发送一次：${error?.message||'未知错误'}`}finally{$('#sendChat').disabled=false}}
$('#sendChat').onclick=sendChat;$('#chatInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendChat()}};$('#clearChat').onclick=async()=>{settings=await window.petAPI.clearChat();renderChat();$('#chatStatus').textContent='聊天记录已清空。'};
$('#heroPet').onclick=()=>{window.petAPI.petCommand('pet');$('#heroBubble').textContent='嘿嘿，摸到我啦～';$('#heroBubble').classList.add('pop');setTimeout(()=>{$('#heroBubble').classList.remove('pop');$('#heroBubble').textContent='我在这里陪你～'},2200)};
document.querySelectorAll('.nav button').forEach(button=>button.onclick=()=>{setPanel(button.dataset.panel);if(button.dataset.panel==='diary')showDiary($('#diaryDate').value||today())});
document.querySelectorAll('[data-feature-panel]').forEach(button=>button.onclick=()=>{const panel=button.dataset.featurePanel;setPanel(panel);if(panel==='diary')showDiary($('#diaryDate').value||today())});
$('#backHome').onclick=()=>setPanel('home');
function syncHeaderExpansion(){document.querySelector('main>header')?.classList.toggle('panel-expanded',$('#mouseProfilePopover').classList.contains('open'))}
function setProfileOpen(open){const popover=$('#mouseProfilePopover');$('#homeBrand').setAttribute('aria-expanded',String(open));popover.setAttribute('aria-hidden',String(!open));popover.classList.toggle('open',open);syncHeaderExpansion()}
$('#homeBrand').onclick=e=>{e.stopPropagation();setProfileOpen(!$('#mouseProfilePopover').classList.contains('open'))};
$('#mouseProfilePopover').onclick=e=>e.stopPropagation();
$('#effectSettingsButton').onclick=()=>setPanel('settings');
$('#pawTrailEnabled').onchange=e=>save({pawTrailEnabled:e.target.checked});
$('#clickEffectEnabled').onchange=e=>save({clickEffectEnabled:e.target.checked});
$('#interfaceLanguage').onchange=e=>save({interfaceLanguage:e.target.value});
$('#settingsPetForm').onchange=async e=>{await save({petForm:e.target.value});$('#formHint').textContent=petFormMessage(e.target.value)};
$('#openUnifiedSettings').onclick=()=>setPanel('settings');
$('#chooseClickEffect').onclick=()=>$('#clickEffectFile').click();
$('#restoreClickEffect').onclick=async()=>{await save({clickEffectDataUrl:''});$('#restoreClickEffect').textContent='已恢复默认鼠鼠';setTimeout(()=>$('#restoreClickEffect').textContent='恢复默认鼠鼠',1400)};
$('#clickEffectFile').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;const source=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});const image=new Image();image.src=source;await image.decode();const max=320,scale=Math.min(1,max/Math.max(image.naturalWidth,image.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));const context=canvas.getContext('2d',{willReadFrequently:true});context.drawImage(image,0,0,canvas.width,canvas.height);const pixels=context.getImageData(0,0,canvas.width,canvas.height),data=pixels.data;for(let i=0;i<data.length;i+=4){const min=Math.min(data[i],data[i+1],data[i+2]),maxChannel=Math.max(data[i],data[i+1],data[i+2]),neutral=maxChannel-min<24;if(neutral&&min>218)data[i+3]=Math.round(data[i+3]*Math.max(0,(252-min)/34))}context.putImageData(pixels,0,0);await save({clickEffectDataUrl:canvas.toDataURL('image/png')});$('#chooseClickEffect').textContent='已自动抠图并保存';setTimeout(()=>$('#chooseClickEffect').textContent='上传自定义点击鼠鼠',1600);e.target.value=''};
document.addEventListener('click',()=>setProfileOpen(false));
document.addEventListener('keydown',e=>{if(e.key==='Escape'){setProfileOpen(false);$('#homeBrand').focus()}});
$('#togglePetTop').onclick=()=>window.petAPI.togglePet();
$('#actionGrid').onclick=async e=>{const rename=e.target.closest('[data-save-action-name]');if(rename){const input=rename.closest('article').querySelector('.action-name-input'),name=input.value.trim();if(!name){$('#actionResult').textContent='动作名称不能为空';input.focus();return}settings=await window.petAPI.renameAction(rename.dataset.saveActionName,name);render();$('#actionResult').textContent=`名称已保存：${name.slice(0,24)}`;return}const remove=e.target.closest('[data-delete-action]');if(remove){settings=await window.petAPI.deleteAction(remove.dataset.deleteAction);render();$('#actionResult').textContent='自定义动作已删除';return}const button=e.target.closest('[data-preview-action]');if(!button)return;await save({petForm:'real'});window.petAPI.petCommand(`action:${button.dataset.previewAction}`);const item=allActions().find(x=>x.id===button.dataset.previewAction);$('#actionResult').textContent=`正在桌面预览：${item.name}`};
$('#importAction').onclick=async()=>{const name=$('#customActionName').value.trim();$('#actionResult').textContent='请选择一个已经透明的动作文件…';const result=await window.petAPI.importAction(name);if(result.cancelled){$('#actionResult').textContent='没有选择文件';return}if(result.error){$('#actionResult').textContent=`添加失败：${result.error}`;return}settings=result.settings;$('#customActionName').value='';render();$('#actionResult').textContent=`已添加动作：${result.item.name}`};
$('#diaryDate').value=today();$('#diaryDate').max=today();$('#diaryDate').onchange=e=>showDiary(e.target.value);$('#diaryArchive').onclick=e=>{const b=e.target.closest('[data-diary-date]');if(b)showDiary(b.dataset.diaryDate)};$('#openDiary').onclick=()=>{setPanel('diary');showDiary(today())};
document.querySelectorAll('[data-quick]').forEach(button=>button.onclick=async()=>{const a=button.dataset.quick;if(a==='pet'){window.petAPI.petCommand('pet');$('#quickResult').textContent='鼠鼠开心地蹭了蹭你！'}else if(a==='feed'){settings=await window.petAPI.feed('leaf');render();$('#quickResult').textContent='鼠鼠抱着菜叶认真地吃起来了。'}else if(a==='form'){const next=nextPetForm(settings.petForm||'3d');await save({petForm:next});$('#quickResult').textContent=petFormMessage(next)}else if(a==='outfit')setPanel('behavior');else if(a==='wheel'){window.petAPI.petCommand('wheel');$('#quickResult').textContent='鼠鼠已经跳上跑轮啦！'}else if(a==='show'){window.petAPI.petCommand('show');$('#quickResult').textContent='鼠鼠已经出来陪你啦！'}setTimeout(refreshHome,300)});
renderAge();renderHeroGreeting();setPanel('home');setTimeout(refreshFeedSummary,500);setInterval(()=>{refreshHome();refreshFeedSummary();renderHeroGreeting()},60000);

/* v12: full-language UI, profile page navigation and page-aware header */
const exactUiText={
  en:{'鼠鼠':'Hamster','你的小仓鼠桌面伙伴':'Your little desktop hamster','出生日期':'Birth date','年龄':'Age','正在计算':'Calculating','体重':'Weight','六十多克':'Over 60 g','性别':'Sex','小男鼠':'Male hamster','作息':'Routine','夜间活跃':'Active at night','喜欢小木屋、菜叶和跑跑轮。':'Loves the wooden house, leafy greens and running wheel.','正在陪伴':'Keeping you company','正在和你一起打字':'Typing with you','正在摸鱼':'Taking a break','心情很好':'Feeling great','正在伸懒腰':'Stretching','正在理毛':'Grooming','正在观察你':'Watching you','正在睡觉':'Sleeping','正在跑跑轮':'Running on the wheel','移动脚印':'Paw-print trail','鼠标点击特效':'Click effect','敲键盘时同步打字':'React while typing','闲置时跑跑轮':'Run wheel when idle','随机说话':'Random speech','真实叫声':'Real sounds','界面语言':'Interface language','鼠鼠形态':'Hamster form','真实动态':'Real animation','上传自定义点击鼠鼠':'Upload custom click effect','上传自定义点击特效':'Upload custom click effect','恢复默认鼠鼠':'Restore default click effect','恢复默认点击特效':'Restore default click effect','上传图片会自动去除接近白色的背景，并只保存在这台电脑。':'Near-white backgrounds are removed automatically. The image stays on this computer.','本地或 AI 陪伴':'Local or AI companion','编辑鼠鼠的话':'Edit Hamster’s lines','查看和添加动作':'View and add actions','形态、习惯和衣服':'Form, habits and outfits','准备喜欢的食物':'Prepare favorite food','收藏每天的陪伴':'Save every day together','宠物主页':'Home','和鼠鼠聊天':'Chat with Hamster','鼠鼠动作库':'Action library','小鼠日记':'Hamster diary','行为与装扮':'Behavior & outfits','对话管理':'Dialogue manager','喂食互动':'Feeding','免费本地聊天':'Free local chat','AI 智能聊天':'AI chat','清空聊天':'Clear chat','发送':'Send','预览':'Preview','保存名称':'Save name','添加透明动作':'Add transparent action','今天':'Today','心情':'Mood','饱食度':'Fullness','下午好，鼠鼠一直在这里':'Good afternoon, Hamster is right here','应用设置':'App settings','所有偏好都集中在这里':'All preferences are collected here'},
  es:{'鼠鼠':'Hámster','你的小仓鼠桌面伙伴':'Tu pequeño hámster de escritorio','出生日期':'Fecha de nacimiento','年龄':'Edad','正在计算':'Calculando','体重':'Peso','六十多克':'Más de 60 g','性别':'Sexo','小男鼠':'Hámster macho','作息':'Rutina','夜间活跃':'Activo por la noche','喜欢小木屋、菜叶和跑跑轮。':'Le gustan la casita, las hojas verdes y la rueda.','正在陪伴':'Acompañándote','正在和你一起打字':'Escribiendo contigo','正在摸鱼':'Tomando un descanso','心情很好':'Muy contento','正在伸懒腰':'Estirándose','正在理毛':'Aseándose','正在观察你':'Observándote','正在睡觉':'Durmiendo','正在跑跑轮':'Corriendo en la rueda','移动脚印':'Rastro de huellas','鼠标点击特效':'Efecto de clic','敲键盘时同步打字':'Reaccionar al escribir','闲置时跑跑轮':'Rueda al estar inactivo','随机说话':'Hablar al azar','真实叫声':'Sonidos reales','界面语言':'Idioma de la interfaz','鼠鼠形态':'Forma de Hámster','真实动态':'Animación real','上传自定义点击鼠鼠':'Subir efecto de clic personalizado','上传自定义点击特效':'Subir efecto de clic personalizado','恢复默认鼠鼠':'Restaurar efecto predeterminado','恢复默认点击特效':'Restaurar efecto predeterminado','上传图片会自动去除接近白色的背景，并只保存在这台电脑。':'El fondo casi blanco se elimina automáticamente. La imagen queda en este equipo.','本地或 AI 陪伴':'Compañía local o con IA','编辑鼠鼠的话':'Editar frases de Hámster','查看和添加动作':'Ver y añadir acciones','形态、习惯和衣服':'Forma, hábitos y ropa','准备喜欢的食物':'Preparar su comida favorita','收藏每天的陪伴':'Guardar cada día juntos','宠物主页':'Inicio','和鼠鼠聊天':'Hablar con Hámster','鼠鼠动作库':'Biblioteca de acciones','小鼠日记':'Diario de Hámster','行为与装扮':'Conducta y ropa','对话管理':'Gestión de diálogos','喂食互动':'Alimentación','免费本地聊天':'Chat local gratuito','AI 智能聊天':'Chat con IA','清空聊天':'Borrar chat','发送':'Enviar','预览':'Vista previa','保存名称':'Guardar nombre','添加透明动作':'Añadir acción transparente','今天':'Hoy','心情':'Ánimo','饱食度':'Saciedad','应用设置':'Ajustes de la aplicación','所有偏好都集中在这里':'Todas las preferencias están aquí'}
};
Object.assign(exactUiText.en,{'3D 模型':'3D model','闲置活动延时':'Idle activity delay','秒后活动':'seconds before activity','中文':'Chinese','模型':'Model','无':'None','原本模样':'Original look','圆眼镜':'Round glasses','蓝领结':'Blue bow tie','生日帽':'Birthday hat','叶子帽':'Leaf hat','行为偏好':'Behavior preferences','自定义鼠鼠的话':'Custom Hamster lines','添加':'Add','行为开关、鼠标特效、形态和语言已经统一移到顶部“设置”中。':'Behavior, pointer effects, form and language are managed in Settings.','给鼠鼠装扮':'Dress up Hamster','保存设置':'Save settings','切换形态':'Switch form','真实动态后续可直接换成鼠鼠的透明视频动作。':'Real animation can use Hamster’s transparent video actions.','可随时切换；程序会记住你上次选择的形态。':'Switch anytime; the app remembers your choice.','鼠鼠会认真理解你刚说的话，并记住最近的聊天内容。':'Hamster understands your message and remembers recent chats.','不联网、不收费，适合日常陪伴':'Offline, free and suitable for daily companionship','理解能力更强，需要自己的 API':'Smarter replies; requires your own API','跟鼠鼠说点什么……（Enter 发送，Shift+Enter 换行）':'Say something to Hamster…','目前共有':'Currently','种真实透明动作，点击即可让桌面鼠鼠演示。':'real transparent actions. Click to preview.','给新动作取个名字':'Name the new action','修改动作名称':'Rename action','鼠鼠的每日小记':'Hamster’s daily notes','每一天都会单独保存，可以随时翻看':'Each day is saved separately for you to revisit.','正在翻开日记本……':'Opening the diary…','鼠鼠的小档案':'Hamster profile','2024 年 6 月 9 日出生，体重六十多克。喜欢住在小木屋里，晚上精力旺盛，最爱跑跑轮。':'Born June 9, 2024, over 60 g. Loves the wooden house and running wheel, and is active at night.','所有陪伴功能，都藏在这只小仓鼠里':'Every companion feature lives around Hamster','今天和鼠鼠':'Today with Hamster','次摸摸':'pets','次投喂':'feeds','次跑轮':'wheel runs','分钟陪伴':'minutes together','鼠鼠现在怎么样':'How is Hamster?','亲密度':'Closeness','快捷照顾':'Quick care','摸摸鼠鼠':'Pet Hamster','喂菜叶':'Feed greens','更换装扮':'Change outfit','让它跑轮':'Run wheel','今天的日记':'Today’s diary','查看完整日记 →':'View full diary →','投喂鼠鼠':'Feed Hamster','每一种食物都会真实出现在鼠鼠手里':'Every food appears in Hamster’s paws','这次喂多少：':'Portion:','尝一口':'A bite','正常份':'Regular','小加餐':'Extra','菜叶':'Leafy greens','面包虫':'Mealworm','小饼干':'Cookie','营养糊糊':'Nutrition paste','随机准备一份':'Prepare a random snack','今日投喂记录':'Today’s feeding record','上次吃了':'Last food','还没有':'None yet','还没有投喂，鼠鼠正在等你～':'No food yet — Hamster is waiting.','应用设置':'App settings'});
Object.assign(exactUiText.es,{'3D 模型':'Modelo 3D','闲置活动延时':'Retraso de actividad','秒后活动':'segundos antes de actividad','中文':'Chino','模型':'Modelo','无':'Ninguno','原本模样':'Aspecto original','圆眼镜':'Gafas redondas','蓝领结':'Pajarita azul','生日帽':'Gorro de cumpleaños','叶子帽':'Sombrero de hoja','行为偏好':'Preferencias de conducta','自定义鼠鼠的话':'Frases personalizadas de Hámster','添加':'Añadir','行为开关、鼠标特效、形态和语言已经统一移到顶部“设置”中。':'La conducta, los efectos, la forma y el idioma se gestionan en Ajustes.','给鼠鼠装扮':'Vestir a Hámster','保存设置':'Guardar ajustes','切换形态':'Cambiar forma','真实动态后续可直接换成鼠鼠的透明视频动作。':'La animación real puede usar vídeos transparentes de Hámster.','可随时切换；程序会记住你上次选择的形态。':'Puedes cambiar cuando quieras; la aplicación recuerda tu elección.','鼠鼠会认真理解你刚说的话，并记住最近的聊天内容。':'Hámster entiende tu mensaje y recuerda los chats recientes.','不联网、不收费，适合日常陪伴':'Sin conexión, gratis y adecuado para acompañarte','理解能力更强，需要自己的 API':'Respuestas más inteligentes; requiere tu propia API','跟鼠鼠说点什么……（Enter 发送，Shift+Enter 换行）':'Di algo a Hámster…','目前共有':'Actualmente','种真实透明动作，点击即可让桌面鼠鼠演示。':'acciones transparentes reales. Haz clic para verlas.','给新动作取个名字':'Nombre de la nueva acción','修改动作名称':'Renombrar acción','鼠鼠的每日小记':'Notas diarias de Hámster','每一天都会单独保存，可以随时翻看':'Cada día se guarda por separado.','正在翻开日记本……':'Abriendo el diario…','鼠鼠的小档案':'Perfil de Hámster','2024 年 6 月 9 日出生，体重六十多克。喜欢住在小木屋里，晚上精力旺盛，最爱跑跑轮。':'Nació el 9 de junio de 2024, pesa más de 60 g y es activo por la noche.','所有陪伴功能，都藏在这只小仓鼠里':'Todas las funciones viven alrededor de Hámster','今天和鼠鼠':'Hoy con Hámster','次摸摸':'caricias','次投喂':'comidas','次跑轮':'carreras','分钟陪伴':'minutos juntos','鼠鼠现在怎么样':'¿Cómo está Hámster?','亲密度':'Afinidad','快捷照顾':'Cuidados rápidos','摸摸鼠鼠':'Acariciar a Hámster','喂菜叶':'Dar hojas','更换装扮':'Cambiar ropa','让它跑轮':'Usar la rueda','今天的日记':'Diario de hoy','查看完整日记 →':'Ver diario completo →','投喂鼠鼠':'Alimentar a Hámster','每一种食物都会真实出现在鼠鼠手里':'Cada alimento aparece en las patas de Hámster','这次喂多少：':'Porción:','尝一口':'Un bocado','正常份':'Normal','小加餐':'Extra','菜叶':'Hojas','面包虫':'Gusano de harina','小饼干':'Galleta','营养糊糊':'Pasta nutritiva','随机准备一份':'Preparar al azar','今日投喂记录':'Comidas de hoy','上次吃了':'Última comida','还没有':'Todavía no','还没有投喂，鼠鼠正在等你～':'Aún no hay comida; Hámster espera.','应用设置':'Ajustes de la aplicación'});
Object.assign(exactUiText.en,{'🏠 免费本地聊天':'🏠 Free local chat','✨ AI 智能聊天':'✨ AI chat','🏠 当前为免费本地模式，不联网，也不会产生任何 API 费用。':'🏠 Free local mode: offline and no API charges.','添加后会和内置台词一起，在点击鼠鼠时轮流出现。':'Added lines rotate with the built-in lines when you click Hamster.','例如：今天也要开心哦':'Example: Let’s be happy today','删除':'Delete','＋ 添加透明动作':'＋ Add transparent action','支持透明 WebP、GIF、APNG、PNG。普通笼内视频暂不自动抠图，避免生成残缺鼠鼠。':'Supports transparent WebP, GIF, APNG and PNG. Cage videos are not auto-cut out to avoid damaged results.','安静坐着':'Sitting quietly','正面静置，轻轻活动小手':'Front-facing idle pose with gentle paw movement','侧头观察':'Looking aside','换一个角度看看桌面':'Looking at the desktop from another angle','低头理毛':'Face grooming','低头整理自己的毛发':'Grooming its fur with head lowered','转身整理':'Back grooming','转身后继续清洁身体':'Turning around to continue grooming','认真吃菜':'Eating greens','抱着菜叶慢慢咀嚼':'Holding and slowly chewing a leaf','继续加餐':'Another snack','另一段真实吃菜动作':'Another real leafy-greens action','装扮会佩戴在头顶、眼睛或颈部；睡觉和跑轮时会暂时收起。':'Accessories sit on the head, eyes or neck and hide during sleep or wheel running.','🎲 随机准备一份':'🎲 Prepare a random snack','清脆慢慢嚼':'Slow crunchy bites','最爱的蛋白加餐':'Favorite protein snack','偶尔奖励一下':'An occasional treat','软软的一小团':'A soft little serving','你':'You','今天':'Today','互动':'Interactions','投喂':'Feeds','跑轮':'Wheel runs'});
Object.assign(exactUiText.es,{'🏠 免费本地聊天':'🏠 Chat local gratuito','✨ AI 智能聊天':'✨ Chat con IA','🏠 当前为免费本地模式，不联网，也不会产生任何 API 费用。':'🏠 Modo local gratuito: sin conexión ni costes de API.','添加后会和内置台词一起，在点击鼠鼠时轮流出现。':'Las frases añadidas se alternan al hacer clic en Hámster.','例如：今天也要开心哦':'Ejemplo: Hoy también estaremos felices','删除':'Eliminar','＋ 添加透明动作':'＋ Añadir acción transparente','支持透明 WebP、GIF、APNG、PNG。普通笼内视频暂不自动抠图，避免生成残缺鼠鼠。':'Admite WebP, GIF, APNG y PNG transparentes. Los vídeos de jaula no se recortan automáticamente.','安静坐着':'Sentado tranquilo','正面静置，轻轻活动小手':'Pose frontal con movimiento suave de patas','侧头观察':'Mirando de lado','换一个角度看看桌面':'Mira el escritorio desde otro ángulo','低头理毛':'Aseo de cara','低头整理自己的毛发':'Se arregla el pelaje con la cabeza baja','转身整理':'Aseo de espalda','转身后继续清洁身体':'Se gira para seguir aseándose','认真吃菜':'Comiendo hojas','抱着菜叶慢慢咀嚼':'Sujeta y mastica lentamente una hoja','继续加餐':'Otra merienda','另一段真实吃菜动作':'Otra acción real comiendo hojas','装扮会佩戴在头顶、眼睛或颈部；睡觉和跑轮时会暂时收起。':'Los accesorios se ocultan al dormir o correr en la rueda.','🎲 随机准备一份':'🎲 Preparar al azar','清脆慢慢嚼':'Mordiscos crujientes','最爱的蛋白加餐':'Proteína favorita','偶尔奖励一下':'Premio ocasional','软软的一小团':'Una porción suave','你':'Tú','今天':'Hoy','互动':'Interacciones','投喂':'Comidas','跑轮':'Carreras'});
Object.assign(exactUiText.en,{'AI 漫剧':'AI Drama','AI 漫剧形态':'AI Drama form','已切换为 AI 漫剧形态，支持呼吸、蹦跳、睡觉、侧躺、开心和爬行。':'Switched to AI Drama with breathing, hopping, sleeping, lying down, happy and crawling animations.'});
Object.assign(exactUiText.es,{'AI 漫剧':'Drama IA','AI 漫剧形态':'Forma Drama IA','已切换为 AI 漫剧形态，支持呼吸、蹦跳、睡觉、侧躺、开心和爬行。':'Se cambió a Drama IA con animaciones de respiración, salto, sueño, tumbado, alegría y gateo.'});
exactUiText.en['▶ 预览']='▶ Preview';
exactUiText.es['▶ 预览']='▶ Vista previa';
exactUiText.en['鼠标移动特效']='Pointer move effect';
exactUiText.es['鼠标移动特效']='Efecto al mover el cursor';
exactUiText.en['只保存在这台电脑']='Stored only on this computer';
exactUiText.es['只保存在这台电脑']='Solo se guarda en este equipo';
exactUiText.en['API 地址']='API endpoint';
exactUiText.es['API 地址']='Dirección de la API';
exactUiText.en['例如 gpt-4o-mini']='For example: gpt-4o-mini';
exactUiText.es['例如 gpt-4o-mini']='Por ejemplo: gpt-4o-mini';
const originalUiText=new WeakMap();
function translateWholeInterface(lang){
  const dict=exactUiText[lang]||{};
  const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,{acceptNode(node){return /\S/.test(node.nodeValue)&&!node.parentElement.closest('script,style')?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT}});
  const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);
  nodes.forEach(node=>{if(!originalUiText.has(node))originalUiText.set(node,node.nodeValue);const raw=originalUiText.get(node),trim=raw.trim(),name=lang==='en'?'Hamster':'Hámster';let translated=lang==='zh'?trim:(dict[trim]||trim.replaceAll('鼠鼠的小日记',lang==='en'?"Hamster’s diary":'Diario de Hámster').replaceAll('鼠鼠',name).replaceAll('小鼠',name));const age=trim.match(/^(\d+)岁(\d+)个月$/);if(lang!=='zh'&&age)translated=lang==='en'?`${age[1]}y ${age[2]}m`:`${age[1]} a ${age[2]} m`;if(lang!=='zh'&&node.parentElement.closest('.diary-title,.diary-stats,#diaryArchive'))translated=translated.replaceAll('今天',lang==='en'?'Today':'Hoy').replaceAll('互动',lang==='en'?'Interactions':'Interacciones').replaceAll('投喂',lang==='en'?'Feeds':'Comidas').replaceAll('跑轮',lang==='en'?'Wheel runs':'Carreras');node.nodeValue=raw.replace(trim,translated)});
  document.querySelectorAll('input[placeholder],textarea[placeholder]').forEach(node=>{if(!node.dataset.zhPlaceholder)node.dataset.zhPlaceholder=node.placeholder;const raw=node.dataset.zhPlaceholder;node.placeholder=lang==='zh'?raw:(dict[raw]||raw)});
  const brand=$('#homeBrand b');if(brand)brand.textContent=lang==='en'?'Hamster':lang==='es'?'Hámster':'鼠鼠';
}
const baseApplyLanguage=applyLanguage;
applyLanguage=function(){baseApplyLanguage();translateWholeInterface(settings?.interfaceLanguage||'zh')};
const baseSetPanel=setPanel;
setPanel=function(name){baseSetPanel(name);applyLanguage()};
$('#homeBrand').onclick=e=>{e.stopPropagation();setPanel('profile')};

/* v17: centered companion controls and independent user feedback flow */
let feedbackFiles=[];
function feedbackPayload(){return {type:document.querySelector('input[name="feedbackType"]:checked')?.value||'其他',description:$('#feedbackDescription')?.value.trim()||'',contact:$('#feedbackContact')?.value.trim()||'',files:feedbackFiles}}
function updateFeedbackState(){if(!$('#feedbackDescription'))return;const length=$('#feedbackDescription').value.length;$('#feedbackCount').textContent=length;$('#submitFeedback').disabled=!$('#feedbackDescription').value.trim();if(!$('#feedbackDescription').value.trim())$('#feedbackStatus').textContent='填写问题描述后即可提交'}
function renderFeedbackFiles(){if(!$('#feedbackFiles'))return;$('#feedbackFiles').innerHTML=feedbackFiles.map(file=>`<li>${escapeHtml(file.name)}</li>`).join('')}
function restoreFeedbackDraft(){const draft=settings?.feedbackDraft;if(!draft||!$('#feedbackDescription'))return;$('#feedbackDescription').value=draft.description||'';$('#feedbackContact').value=draft.contact||'';const type=document.querySelector(`input[name="feedbackType"][value="${CSS.escape(draft.type||'功能异常')}"]`);if(type)type.checked=true;feedbackFiles=Array.isArray(draft.files)?draft.files:[];renderFeedbackFiles();updateFeedbackState()}
$('#feedbackButton').onclick=()=>setPanel('feedback');
$('#feedbackDescription').oninput=updateFeedbackState;
$('#chooseFeedbackFiles').onclick=async()=>{feedbackFiles=await window.petAPI.chooseFeedbackFiles();renderFeedbackFiles();$('#feedbackStatus').textContent=feedbackFiles.length?'已选择附件，请在打开的 GitHub 页面中手动添加':'没有选择附件'};
$('#saveFeedbackDraft').onclick=async()=>{await save({feedbackDraft:feedbackPayload()});$('#feedbackStatus').textContent='草稿已保存在这台电脑'};
$('#viewFeedbackIssues').onclick=()=>window.petAPI.openFeedbackIssues();
$('#feedbackForm').onsubmit=async e=>{e.preventDefault();const payload=feedbackPayload();if(!payload.description)return updateFeedbackState();$('#submitFeedback').disabled=true;$('#feedbackStatus').textContent='正在打开 GitHub 反馈页面…';const result=await window.petAPI.submitFeedback(payload);$('#submitFeedback').disabled=false;$('#feedbackStatus').textContent=result?.ok?'已打开 GitHub，请检查内容并点击提交':result?.error||'暂时无法打开反馈页面'};
window.petAPI.getSettings().then(()=>restoreFeedbackDraft());
Object.assign(exactUiText.en,{'反馈':'Feedback','问题反馈':'Feedback','告诉我们哪里需要改进':'Tell us what we can improve','查看公开反馈 ↗':'View public feedback ↗','反馈类型':'Feedback type','功能异常':'Bug','使用建议':'Suggestion','界面问题':'Interface issue','其他':'Other','问题描述':'Description','请描述你遇到的问题，以及你希望看到的效果……':'Describe what happened and what you expected…','联系方式（选填）':'Contact (optional)','邮箱或其他联系方式':'Email or another contact method','添加截图或视频':'Add screenshots or video','附件不会自动上传，请在打开的 GitHub 页面中确认后添加':'Attachments are not uploaded automatically. Add them on the GitHub page.','选择附件':'Choose files','填写问题描述后即可提交':'Add a description to submit','保存草稿':'Save draft','提交反馈':'Submit feedback'});
Object.assign(exactUiText.es,{'反馈':'Comentarios','问题反馈':'Comentarios','告诉我们哪里需要改进':'Dinos qué podemos mejorar','查看公开反馈 ↗':'Ver comentarios públicos ↗','反馈类型':'Tipo de comentario','功能异常':'Error','使用建议':'Sugerencia','界面问题':'Problema de interfaz','其他':'Otro','问题描述':'Descripción','请描述你遇到的问题，以及你希望看到的效果……':'Describe lo ocurrido y el resultado esperado…','联系方式（选填）':'Contacto (opcional)','邮箱或其他联系方式':'Correo u otro medio de contacto','添加截图或视频':'Añadir capturas o vídeo','附件不会自动上传，请在打开的 GitHub 页面中确认后添加':'Los archivos no se suben automáticamente. Añádelos en GitHub.','选择附件':'Elegir archivos','填写问题描述后即可提交':'Añade una descripción para enviar','保存草稿':'Guardar borrador','提交反馈':'Enviar comentario'});

/* v18: multilingual local-chat prompts */
const localChatSuggestions={
  zh:{title:'可以问鼠鼠',items:['你今天心情怎么样？','你饿了吗？','你最喜欢吃什么？','你在做什么？','你什么时候生日？','你为什么喜欢跑轮？','可以陪我一会儿吗？','我今天很累，安慰我一下']},
  en:{title:'Ask Hamster',items:['How are you feeling today?','Are you hungry?','What is your favorite food?','What are you doing?','When is your birthday?','Why do you like your wheel?','Can you stay with me?','I had a hard day. Can you comfort me?']},
  es:{title:'Pregunta a Hámster',items:['¿Cómo te sientes hoy?','¿Tienes hambre?','¿Cuál es tu comida favorita?','¿Qué estás haciendo?','¿Cuándo es tu cumpleaños?','¿Por qué te gusta la rueda?','¿Puedes acompañarme?','Tuve un día difícil. ¿Puedes animarme?']}
};
function renderChatSuggestions(){const root=$('#chatSuggestions');if(!root||!settings)return;const copy=localChatSuggestions[settings.interfaceLanguage||'zh']||localChatSuggestions.zh;root.querySelector('b').textContent=copy.title;root.querySelector('div').innerHTML=copy.items.map(question=>`<button type="button" data-chat-question="${escapeHtml(question)}">${escapeHtml(question)}</button>`).join('')}
$('#chatSuggestions').onclick=e=>{const button=e.target.closest('[data-chat-question]');if(!button)return;$('#chatInput').value=button.dataset.chatQuestion;sendChat()};
const chatSuggestionTrack=$('#chatSuggestions>div');
chatSuggestionTrack.addEventListener('wheel',e=>{if(chatSuggestionTrack.scrollWidth<=chatSuggestionTrack.clientWidth)return;e.preventDefault();chatSuggestionTrack.scrollBy({left:e.deltaX||e.deltaY,behavior:'smooth'})},{passive:false});
chatSuggestionTrack.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();chatSuggestionTrack.scrollBy({left:e.key==='ArrowRight'?220:-220,behavior:'smooth'})});
let chatSuggestionDrag=null;
let suppressSuggestionClick=false;
chatSuggestionTrack.addEventListener('pointerdown',e=>{
  if(e.pointerType!=='mouse'||e.button!==0||chatSuggestionTrack.scrollWidth<=chatSuggestionTrack.clientWidth)return;
  chatSuggestionDrag={id:e.pointerId,x:e.clientX,scrollLeft:chatSuggestionTrack.scrollLeft,moved:false};
  chatSuggestionTrack.setPointerCapture(e.pointerId);
  chatSuggestionTrack.classList.add('dragging');
});
chatSuggestionTrack.addEventListener('pointermove',e=>{
  if(!chatSuggestionDrag||chatSuggestionDrag.id!==e.pointerId)return;
  const distance=e.clientX-chatSuggestionDrag.x;
  if(Math.abs(distance)>4)chatSuggestionDrag.moved=true;
  chatSuggestionTrack.scrollLeft=chatSuggestionDrag.scrollLeft-distance;
});
function finishSuggestionDrag(e){
  if(!chatSuggestionDrag||chatSuggestionDrag.id!==e.pointerId)return;
  suppressSuggestionClick=chatSuggestionDrag.moved;
  chatSuggestionDrag=null;
  chatSuggestionTrack.classList.remove('dragging');
  if(chatSuggestionTrack.hasPointerCapture(e.pointerId))chatSuggestionTrack.releasePointerCapture(e.pointerId);
  if(suppressSuggestionClick)setTimeout(()=>{suppressSuggestionClick=false},0);
}
chatSuggestionTrack.addEventListener('pointerup',finishSuggestionDrag);
chatSuggestionTrack.addEventListener('pointercancel',finishSuggestionDrag);
chatSuggestionTrack.addEventListener('click',e=>{if(!suppressSuggestionClick)return;e.preventDefault();e.stopImmediatePropagation()},{capture:true});
const applyLanguageWithSuggestions=applyLanguage;
applyLanguage=function(){applyLanguageWithSuggestions();renderChatSuggestions()};

const defaultShortcutMap={togglePet:'Alt+Shift+H',openControl:'Ctrl+Alt+H',pet:'Ctrl+Alt+P',feed:'Ctrl+Alt+E',wheel:'Ctrl+Alt+W',switchForm:'Ctrl+Alt+F'};
const shortcutTranslations={
  zh:{title:'便捷键',subtitle:'在其他应用里也可以快速照顾鼠鼠',reset:'恢复默认',hint:'点击按键框，然后按下新的组合键',recording:'请按下新的组合键，Esc 取消',saved:'便捷键已保存并立即生效',resetDone:'已恢复默认便捷键',conflict:'这个组合键已被其他功能使用',invalid:'请使用包含 Ctrl、Alt 或 Shift 的组合键',unavailable:'该组合键被系统或其他应用占用，请换一个',actions:{togglePet:['显示或隐藏鼠鼠','无需打开控制中心'],openControl:['打开控制中心','查看功能与设置'],pet:['摸摸鼠鼠','快速增加一次互动'],feed:['喂一口菜叶','直接投喂常用食物'],wheel:['让鼠鼠跑轮','立即播放跑轮动作'],switchForm:['切换鼠鼠形态','在 3D 与真实动态间切换']}},
  en:{title:'Keyboard shortcuts',subtitle:'Care for Hamster while using other apps',reset:'Restore defaults',hint:'Select a shortcut, then press a new key combination',recording:'Press a new combination, or Esc to cancel',saved:'Shortcut saved and active',resetDone:'Default shortcuts restored',conflict:'This combination is already used by another action',invalid:'Include Ctrl, Alt, or Shift in the shortcut',unavailable:'This shortcut is occupied by the system or another app',actions:{togglePet:['Show or hide Hamster','No need to open the control center'],openControl:['Open control center','View features and settings'],pet:['Pet Hamster','Quickly add one interaction'],feed:['Feed a leafy bite','Give Hamster the usual snack'],wheel:['Run on the wheel','Play the wheel action now'],switchForm:['Switch Hamster form','Toggle between 3D and real motion']}},
  es:{title:'Atajos de teclado',subtitle:'Cuida a Hámster mientras usas otras aplicaciones',reset:'Restaurar valores',hint:'Selecciona un atajo y pulsa una nueva combinación',recording:'Pulsa una combinación nueva o Esc para cancelar',saved:'Atajo guardado y activo',resetDone:'Se restauraron los atajos predeterminados',conflict:'Esta combinación ya está asignada a otra acción',invalid:'Incluye Ctrl, Alt o Shift en el atajo',unavailable:'El sistema u otra aplicación ya usa este atajo',actions:{togglePet:['Mostrar u ocultar a Hámster','Sin abrir el centro de control'],openControl:['Abrir el centro de control','Ver funciones y ajustes'],pet:['Acariciar a Hámster','Añadir rápidamente una interacción'],feed:['Dar una hoja','Ofrecer su comida habitual'],wheel:['Correr en la rueda','Iniciar ahora la animación'],switchForm:['Cambiar forma de Hámster','Alternar entre 3D y movimiento real']}}
};
shortcutTranslations.zh.actions.switchForm=['切换鼠鼠形态','依次切换 3D、AI 漫剧与真实动态'];
shortcutTranslations.en.actions.switchForm=['Switch Hamster form','Cycle through 3D, AI Drama and real motion'];
shortcutTranslations.es.actions.switchForm=['Cambiar forma de Hámster','Alternar entre 3D, Drama IA y movimiento real'];
let recordingShortcut='';
const currentShortcuts=()=>({...defaultShortcutMap,...(settings?.shortcuts||{})});
function shortcutStatus(message,state=''){
  const node=$('#shortcutStatus');if(!node)return;
  node.textContent=message;node.dataset.state=state;
}
function renderShortcutSettings(){
  const grid=$('#shortcutGrid');if(!grid||!settings)return;
  const lang=settings.interfaceLanguage||'zh',copy=shortcutTranslations[lang]||shortcutTranslations.zh,shortcuts=currentShortcuts();
  const heading=$('.shortcut-heading');heading.querySelector('b').textContent=copy.title;heading.querySelector('span').textContent=copy.subtitle;$('#resetShortcuts').textContent=copy.reset;
  grid.innerHTML=Object.entries(copy.actions).map(([action,[label,description]])=>`<article class="shortcut-item"><span><b>${escapeHtml(label)}</b><small>${escapeHtml(description)}</small></span><button type="button" class="shortcut-key${recordingShortcut===action?' recording':''}" data-shortcut-action="${action}">${recordingShortcut===action?'…':escapeHtml(shortcuts[action])}</button></article>`).join('');
  if(!recordingShortcut&&!$('#shortcutStatus').dataset.state)shortcutStatus(copy.hint);
}
function eventToAccelerator(event){
  const modifierNames=['Control','Alt','Shift','Meta'];if(modifierNames.includes(event.key))return '';
  const parts=[];if(event.ctrlKey)parts.push('Ctrl');if(event.altKey)parts.push('Alt');if(event.shiftKey)parts.push('Shift');if(event.metaKey)parts.push('Super');
  const aliases={' ':'Space',ArrowUp:'Up',ArrowDown:'Down',ArrowLeft:'Left',ArrowRight:'Right',Escape:'Esc'};
  let key=aliases[event.key]||event.key;if(key.length===1)key=key.toUpperCase();parts.push(key);return parts.join('+');
}
$('#shortcutGrid')?.addEventListener('click',event=>{
  const button=event.target.closest('[data-shortcut-action]');if(!button)return;
  recordingShortcut=button.dataset.shortcutAction;shortcutStatus((shortcutTranslations[settings.interfaceLanguage||'zh']||shortcutTranslations.zh).recording,'recording');renderShortcutSettings();
});
document.addEventListener('keydown',async event=>{
  if(!recordingShortcut)return;
  event.preventDefault();event.stopImmediatePropagation();
  const copy=shortcutTranslations[settings.interfaceLanguage||'zh']||shortcutTranslations.zh;
  if(event.key==='Escape'){recordingShortcut='';shortcutStatus(copy.hint,'');renderShortcutSettings();return}
  const accelerator=eventToAccelerator(event);if(!accelerator)return;
  if(!(event.ctrlKey||event.altKey||event.shiftKey||event.metaKey)&&!/^F(?:[1-9]|1[0-2])$/i.test(event.key)){shortcutStatus(copy.invalid,'error');return}
  const action=recordingShortcut,shortcuts=currentShortcuts(),duplicate=Object.entries(shortcuts).find(([key,value])=>key!==action&&value.toLowerCase()===accelerator.toLowerCase());
  if(duplicate){shortcutStatus(copy.conflict,'error');return}
  recordingShortcut='';const result=await window.petAPI.saveShortcuts({...shortcuts,[action]:accelerator});settings=result.settings;
  const registration=result.results?.[action];shortcutStatus(registration?.ok?copy.saved:copy.unavailable,registration?.ok?'success':'error');renderShortcutSettings();
},{capture:true});
$('#resetShortcuts')?.addEventListener('click',async()=>{
  recordingShortcut='';const copy=shortcutTranslations[settings.interfaceLanguage||'zh']||shortcutTranslations.zh,result=await window.petAPI.resetShortcuts();settings=result.settings;shortcutStatus(copy.resetDone,'success');renderShortcutSettings();
});
const applyLanguageWithShortcuts=applyLanguage;
applyLanguage=function(){applyLanguageWithShortcuts();renderShortcutSettings()};
