const $=s=>document.querySelector(s);let settings;const foodNames={leaf:'菜叶',worm:'面包虫',cookie:'小饼干',paste:'营养糊糊'};let feedPortion=1;
const hamsterActions=[
  {id:'idle-a',icon:'🐹',name:'安静坐着',desc:'正面静置，轻轻活动小手'},
  {id:'idle-b',icon:'👀',name:'侧头观察',desc:'换一个角度看看桌面'},
  {id:'groom-a',icon:'🧼',name:'低头理毛',desc:'低头整理自己的毛发'},
  {id:'groom-b',icon:'🌀',name:'转身整理',desc:'转身后继续清洁身体'},
  {id:'eat-a',icon:'🥬',name:'认真吃菜',desc:'抱着菜叶慢慢咀嚼'},
  {id:'eat-b',icon:'😋',name:'继续加餐',desc:'另一段真实吃菜动作'}
];
function escapeHtml(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
function render(){if(!settings)return;['keyboardReaction','idleWheel','randomTalk','soundEnabled'].forEach(k=>$('#'+k).checked=!!settings[k]);$('#idleDelay').value=settings.idleDelay;$('#delayText').textContent=settings.idleDelay;$('#mood').textContent=settings.mood+'%';$('#hunger').textContent=settings.hunger+'%';$('#moodBar').style.width=settings.mood+'%';$('#hungerBar').style.width=settings.hunger+'%';document.querySelectorAll('[data-outfit]').forEach(b=>b.classList.toggle('active',b.dataset.outfit===settings.outfit));document.querySelectorAll('[data-form]').forEach(b=>b.classList.toggle('active',b.dataset.form===(settings.petForm||'3d')));$('#lineList').innerHTML=(settings.customLines||[]).map((x,i)=>`<div class="line"><span>${escapeHtml(x)}</span><button data-remove="${i}">删除</button></div>`).join('')||'<p class="hint">还没有自定义台词</p>';renderActionLibrary()}
async function save(p){settings=await window.petAPI.saveSettings(p);render();return settings}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function setPanel(name){document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.panel===name));document.querySelectorAll('.panel-section').forEach(s=>s.classList.toggle('active',s.dataset.section===name))}
function allActions(){return [...hamsterActions.map(a=>({...a,name:settings?.actionNames?.[a.id]||a.name})),...(settings?.customActions||[]).map(a=>({...a,icon:'✨',desc:'你添加的自定义透明动作',custom:true}))]}
function renderActionLibrary(){const list=allActions();$('#actionCount').textContent=list.length;$('#actionGrid').innerHTML=list.map((a,i)=>`<article><div class="action-info"><i>${a.icon}</i><b>${i+1}. ${escapeHtml(a.name)}</b><p>${a.desc}</p><input class="action-name-input" maxlength="24" value="${escapeHtml(a.name)}" aria-label="修改动作名称"></div><div class="action-buttons"><button data-preview-action="${a.id}">▶ 预览</button><button class="rename-action" data-save-action-name="${a.id}">保存名称</button>${a.custom?`<button class="delete-action" data-delete-action="${a.id}">删除</button>`:''}</div></article>`).join('')}
async function renderDiaryArchive(selected){const list=await window.petAPI.getDiaryList();$('#diaryArchive').innerHTML=list.length?list.map(e=>`<button data-diary-date="${e.date}" class="${e.date===selected?'active':''}"><b>${e.date===today()?'今天':e.date}</b><span>${escapeHtml(e.body.slice(0,25))}…</span></button>`).join(''):'<p class="hint">今天将是第一篇日记</p>'}
async function showDiary(date){const e=await window.petAPI.getDiary(date);$('#diaryDate').value=e.date;$('#diaryPaper').innerHTML=`<div class="diary-title">${escapeHtml(e.title)}</div><p>${escapeHtml(e.body)}</p><div class="diary-stats"><span>💗 互动 ${e.stats.interactions}</span><span>🥬 投喂 ${e.stats.feeds}</span><span>🎡 跑轮 ${e.stats.wheel}</span></div><div class="paw">🐾 鼠鼠</div>`;await renderDiaryArchive(e.date)}
function renderAge(){const now=new Date(),born=new Date(2024,5,9),days=Math.floor((now-born)/86400000);let years=now.getFullYear()-born.getFullYear(),months=now.getMonth()-born.getMonth();if(now.getDate()<born.getDate())months--;if(months<0){years--;months+=12}$('#ageText').textContent=`🎂 ${years}岁${months}个月 · 来到世界${days}天`;let birthday=new Date(now.getFullYear(),5,9);if(birthday<new Date(now.getFullYear(),now.getMonth(),now.getDate()))birthday=new Date(now.getFullYear()+1,5,9);const left=Math.ceil((birthday-new Date(now.getFullYear(),now.getMonth(),now.getDate()))/86400000);$('#birthdayText').textContent=left===0?'🎉 今天生日！':`🎈 距生日 ${left} 天`}
async function refreshHome(){if(!settings)return;const o=await window.petAPI.getOverview();$('#todayInteractions').textContent=o.day.interactions;$('#todayFeeds').textContent=o.day.feeds;$('#todayWheel').textContent=o.day.wheel;$('#todayMinutes').textContent=o.minutes;const points=o.totals.interactions*2+o.totals.feeds*5+o.totals.wheel*3,levels=[['初次见面',0,30],['熟悉的气味',30,100],['最信任的主人',100,250],['永远的小伙伴',250,500]],index=levels.findIndex((x,i)=>points<x[2]||i===levels.length-1),level=levels[index];$('#affinityLevel').textContent=`Lv.${index+1} ${level[0]}`;$('#affinityBar').style.width=`${Math.min(100,(points-level[1])/(level[2]-level[1])*100)}%`;$('#affinityText').textContent=index===levels.length-1?'鼠鼠最信任的人就是你。':`亲密值 ${points} · 距离下一等级还差 ${Math.max(0,level[2]-points)}`;$('#diaryPreview').textContent=o.diary.body;$('#previewStats').innerHTML=`<span>💗 ${o.day.interactions} 次互动</span><span>🥬 ${o.day.feeds} 次投喂</span><span>🎡 ${o.day.wheel} 次跑轮</span>`;$('#statusText').textContent=settings.mood>=85&&settings.hunger>=70?'心情很好，肚子也很满足':settings.hunger<50?'肚子有一点饿了':settings.mood<60?'今天想让你多陪陪':'正在安静地陪着你'}
window.petAPI.getSettings().then(s=>{settings=s;render();refreshHome()});window.petAPI.onSettings(s=>{settings=s;render()});
window.petAPI.onStatus(status=>{$('#liveStatus').textContent=status;$('#homeStatus').textContent=status;$('#statusFace').textContent=status.includes('睡')?'😴':status.includes('跑')?'🐹💨':status.includes('开心')?'🥰':'🐹'});
['keyboardReaction','idleWheel','randomTalk','soundEnabled'].forEach(k=>$('#'+k).onchange=e=>save({[k]:e.target.checked}));$('#idleDelay').oninput=e=>{$('#delayText').textContent=e.target.value};$('#idleDelay').onchange=e=>save({idleDelay:Number(e.target.value)});
async function feedMouse(food){settings=await window.petAPI.feed(food,feedPortion);$('#feedResult').textContent=food==='leaf'?'鼠鼠把菜叶抱在手里，正在一口一口慢慢吃。':`鼠鼠接过${foodNames[food]}，开始认真享用啦！`;render();await refreshHome();await refreshFeedSummary()}
async function refreshFeedSummary(){if(!settings||!$('#feedCounts'))return;const o=await window.petAPI.getOverview(),counts=o.day.feedDetails||{},text=Object.entries(counts).filter(([,n])=>n).map(([k,n])=>`${foodNames[k]||k} ${n}口`).join(' · ');$('#feedCounts').textContent=text||'还没有投喂，鼠鼠正在等你～';$('#lastFood').textContent=foodNames[settings.lastFood]||'还没有'}
document.querySelectorAll('[data-outfit]').forEach(b=>b.onclick=()=>save({outfit:b.dataset.outfit}));document.querySelectorAll('[data-food]').forEach(b=>b.onclick=()=>feedMouse(b.dataset.food));
document.querySelectorAll('[data-portion]').forEach(b=>b.onclick=()=>{feedPortion=Number(b.dataset.portion);document.querySelectorAll('[data-portion]').forEach(x=>x.classList.toggle('active',x===b))});
$('#randomFood').onclick=()=>{const foods=['leaf','worm','cookie','paste'];feedMouse(foods[Math.floor(Math.random()*foods.length)])};
document.querySelectorAll('[data-form]').forEach(b=>b.onclick=async()=>{await save({petForm:b.dataset.form});$('#formHint').textContent=b.dataset.form==='3d'?'已切换为 3D 模型，可按住鼠鼠旋转。':'已切换为真实动态；后续会替换成鼠鼠的透明视频动作。'});
$('#addLine').onclick=()=>{const v=$('#newLine').value.trim();if(!v)return;save({customLines:[...(settings.customLines||[]),v]});$('#newLine').value=''};$('#lineList').onclick=e=>{if(e.target.dataset.remove!==undefined){const a=[...settings.customLines];a.splice(Number(e.target.dataset.remove),1);save({customLines:a})}};$('#togglePet').onclick=()=>window.petAPI.togglePet();
document.querySelectorAll('.nav button').forEach(button=>button.onclick=()=>{setPanel(button.dataset.panel);if(button.dataset.panel==='diary')showDiary($('#diaryDate').value||today())});
$('#actionGrid').onclick=async e=>{const rename=e.target.closest('[data-save-action-name]');if(rename){const input=rename.closest('article').querySelector('.action-name-input'),name=input.value.trim();if(!name){$('#actionResult').textContent='动作名称不能为空';input.focus();return}settings=await window.petAPI.renameAction(rename.dataset.saveActionName,name);render();$('#actionResult').textContent=`名称已保存：${name.slice(0,24)}`;return}const remove=e.target.closest('[data-delete-action]');if(remove){settings=await window.petAPI.deleteAction(remove.dataset.deleteAction);render();$('#actionResult').textContent='自定义动作已删除';return}const button=e.target.closest('[data-preview-action]');if(!button)return;await save({petForm:'real'});window.petAPI.petCommand(`action:${button.dataset.previewAction}`);const item=allActions().find(x=>x.id===button.dataset.previewAction);$('#actionResult').textContent=`正在桌面预览：${item.name}`};
$('#importAction').onclick=async()=>{const name=$('#customActionName').value.trim();$('#actionResult').textContent='请选择一个已经透明的动作文件…';const result=await window.petAPI.importAction(name);if(result.cancelled){$('#actionResult').textContent='没有选择文件';return}if(result.error){$('#actionResult').textContent=`添加失败：${result.error}`;return}settings=result.settings;$('#customActionName').value='';render();$('#actionResult').textContent=`已添加动作：${result.item.name}`};
$('#diaryDate').value=today();$('#diaryDate').max=today();$('#diaryDate').onchange=e=>showDiary(e.target.value);$('#diaryArchive').onclick=e=>{const b=e.target.closest('[data-diary-date]');if(b)showDiary(b.dataset.diaryDate)};$('#openDiary').onclick=()=>{setPanel('diary');showDiary(today())};
document.querySelectorAll('[data-quick]').forEach(button=>button.onclick=async()=>{const a=button.dataset.quick;if(a==='pet'){window.petAPI.petCommand('pet');$('#quickResult').textContent='鼠鼠开心地蹭了蹭你！'}else if(a==='feed'){settings=await window.petAPI.feed('leaf');render();$('#quickResult').textContent='鼠鼠抱着菜叶认真地吃起来了。'}else if(a==='actions')setPanel('actions');else if(a==='outfit')setPanel('behavior');else if(a==='wheel'){window.petAPI.petCommand('wheel');$('#quickResult').textContent='鼠鼠已经跳上跑轮啦！'}else if(a==='show'){window.petAPI.petCommand('show');$('#quickResult').textContent='鼠鼠已经出来陪你啦！'}setTimeout(refreshHome,300)});
renderActionLibrary();renderAge();setTimeout(refreshFeedSummary,500);setInterval(()=>{refreshHome();refreshFeedSummary()},60000);
