(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.TownPets=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
 const DAY=86400000,candidates=[{id:'cat',name:'蜜桃',kind:'猫'},{id:'dog',name:'奶糖',kind:'狗'}],prices={visit:3,food:5,bed:8,toy:4};
 const species=[['beaver','海狸'],['bee','蜜蜂'],['bunny','兔子'],['cat','猫'],['caterpillar','毛毛虫'],['chick','小鸡'],['cow','奶牛'],['crab','螃蟹'],['deer','鹿'],['dog','狗'],['elephant','大象'],['fish','鱼'],['fox','狐狸'],['giraffe','长颈鹿'],['hog','野猪'],['koala','考拉'],['lion','狮子'],['monkey','猴子'],['panda','熊猫'],['parrot','鹦鹉'],['penguin','企鹅'],['pig','小猪'],['polar','北极熊'],['tiger','老虎']].map(([id,name])=>({id,name}));
 const residents=state=>[...(state.npcs||[]),...(state.offspring||[]),...(state.npcOffspring||[])].filter(n=>n.alive!==false&&!n.transferredToMain&&n.id!==state.mainId);
 function restock(home){if(home.stock.length)return;home.batch=(home.batch||0)+1;home.stock=Array.from({length:2},(_,i)=>{const animal=species[((home.batch-1)*2+i)%species.length],id='pet-'+(++home.serial);return {id,species:animal.id,kind:animal.name,name:animal.name+'伙伴'+home.serial}})}
 function shopOwner(state){const home=state.petHome,list=residents(state);let owner=list.find(n=>n.id===home.ownerId);if(!owner){owner=list.find(n=>n.place==='宠物之家')||list.find(n=>['小镇居民','小镇新邻居','广场邻居','小屋邻居'].includes(n.role))||list.find(n=>list.filter(p=>p.place===n.place).length>1);if(owner){home.ownerId=owner.id;owner.petPreviousJob={role:owner.role,place:owner.place}}}if(owner){owner.role='宠物店老板';owner.place='宠物之家'}return owner}
 function normalize(state){const old=state.petHome||{};state.petHome={pets:[],food:0,follow:false,facilities:{bed:false,toy:false},income:[],incomeSince:state.calendarTime,...old,pets:(old.pets||[]).map(p=>({...p})),facilities:{bed:false,toy:false,...old.facilities},income:(old.income||[]).map(e=>({...e}))};const home=state.petHome;home.npcPets=(old.npcPets||[]).map(p=>({...p}));const liveIds=new Set(residents(state).map(n=>n.id));home.invites=(old.invites||[]).map(p=>({...p,status:liveIds.has(p.npcId)?p.status:'cancelled'}));home.serial=Math.max(Number(old.serial)||0,...[...home.pets,...home.npcPets,...(old.stock||[])].map(p=>Number(String(p.id).split('-').at(-1))||0));home.pets.forEach(p=>p.species=p.species||p.id);home.stock=Array.isArray(old.stock)?old.stock.map(p=>({...p})):candidates.filter(p=>!home.pets.some(o=>o.id===p.id)).map(p=>({...p,species:p.id}));restock(home);shopOwner(state);return home}
 function recordIncome(state,amount){const home=normalize(state),day=Math.floor(state.calendarTime/DAY);if(amount<=0)return;const entry=home.income.find(e=>e.day===day);if(entry)entry.amount+=amount;else home.income.push({day,amount});home.income=home.income.filter(e=>e.day>=day-7)}
 function adoptionPrice(state){const home=state.petHome||normalize(state),day=Math.floor(state.calendarTime/DAY),entries=home.income.filter(e=>e.day>=day-6&&e.day<=day),days=Math.min(7,Math.max(1,day-Math.floor(home.incomeSince/DAY)+1));const average=entries.length?entries.reduce((sum,e)=>sum+e.amount,0)/days:10;return {average,cost:Math.max(1,Math.ceil(average*.5)),days}}
 function settle(state,from,to,time=Date.now()){const home=normalize(state),days=Math.max(0,Math.floor(to/DAY)-Math.floor(from/DAY));if(!days||!home.pets.length)return;for(let day=0;day<days;day++)for(const pet of home.pets){const fed=home.food>0;if(fed)home.food--;pet.fullness=Math.max(0,Math.min(100,(pet.fullness??80)+(fed?20:-20)))}if(home.food===0&&home.lastFoodNotice!==Math.floor(to/DAY)){home.lastFoodNotice=Math.floor(to/DAY);const e={id:'pet-food-'+to,time,calendarTime:to,type:'pet',place:'鼠鼠小屋',text:'鼠鼠小屋：宠物粮用完了，请及时补给照顾猫狗伙伴。'};state.notifications=[...(state.notifications||[]),e].slice(-30)}}
 function perform(input,action,{consent=false,time=Date.now(),petId,speciesId,image,npcIds=[]}={}){const sim=typeof module==='object'&&module.exports?require('./town-sim.js'):globalThis.TownSimulation,state=sim.migrate(structuredClone(input),time),home=normalize(state),fail=message=>({state,ok:false,message});if(!state.alive)return fail('请先选择新的主鼠。');if(sim.mainSleeping(state))return sim.sleepBlocked(state);
  const selected=petId?home.pets.filter(p=>p.id===petId):home.pets;if(petId&&!selected.length&&!['custom-texture'].includes(action))return fail('这只宠物尚未领养。');let cost=0,text='';
  if(action.startsWith('adopt-')){const pet=home.stock.find(p=>p.id===action.slice(6));if(!pet)return fail('没有这只待领养的宠物。');if(home.pets.some(p=>p.id===pet.id))return fail('这只宠物已经是小镇的伙伴了。');if(!consent)return fail('请先确认会持续照顾宠物，领养后不提供弃养。');cost=adoptionPrice(state).cost;if(state.seeds<cost)return fail('瓜子不足，领养需要 '+cost+' 颗。');home.pets.push({...pet,adoptedSlot:home.stock.indexOf(pet),adoptedAt:state.calendarTime,fullness:80});home.stock=home.stock.filter(p=>p.id!==pet.id);restock(home);home.follow=true;text=state.mainName+'领养了'+pet.kind+'伙伴'+pet.name+'，它会跟随主鼠，回小屋生活。'}
  else if(action==='request-species'){const animal=species.find(s=>s.id===speciesId);if(!animal)return fail('请从老板提供的24个物种中选择。');cost=5;if(state.seeds<cost)return fail('指定物种需要5颗瓜子。');const id='pet-'+(++home.serial);home.stock[0]={id,species:animal.id,kind:animal.name,name:animal.name+'伙伴'+home.serial};text='老板准备了一只'+animal.name+'，可在待领养列表中查看；领养费另计。'}
  else if(action==='custom-texture'){const pet=home.stock.find(p=>p.id===petId);if(!pet)return fail('请选择店内待领养宠物。');if(typeof image!=='string'||image.length>350000||!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(image))return fail('请选择有效的图片。');cost=5;if(state.seeds<cost)return fail('图片贴图定制需要5颗瓜子。');pet.texture=image;text='图片已贴到'+pet.kind+'模型表面；立体形状保持原样，领养费另计。'}
  else if(action==='invite-npcs'){const ids=[...new Set(npcIds)],list=residents(state),chosen=ids.map(id=>list.find(n=>n.id===id));if(!ids.length||chosen.some(n=>!n))return fail('请选择现有在世NPC居民，不能选择主鼠。');const reserved=new Set([...home.npcPets.filter(p=>list.some(n=>n.id===p.ownerId)).map(p=>p.ownerId),...home.invites.filter(p=>p.status!=='cancelled').map(p=>p.npcId),...ids]);if(reserved.size>5)return fail('最多允许5位NPC领养宠物，包含已领养和已安排的居民。');for(const npc of chosen)if(!home.invites.some(p=>p.npcId===npc.id&&p.status!=='cancelled')&&!home.npcPets.some(p=>p.ownerId===npc.id))home.invites.push({npcId:npc.id,status:'pending'});text='主鼠将依次通知所选居民，好感度各增加10，然后由他们自主到店领养；不消耗主鼠体力。'}
  else if(action==='follow'){if(!home.pets.length)return fail('先领养宠物，再选择跟随。');home.follow=!home.follow;text=home.follow?'宠物开始跟随主鼠。':'宠物会回鼠鼠小屋等待。'}
  else if(action==='visit'){if(home.visitUntil>state.calendarTime)return fail('今天的陪伴体验仍在有效期内。');cost=prices.visit;home.visitUntil=state.calendarTime+DAY;text='开启一天猫狗陪伴体验，可在陪伴区与宠物互动。'}
  else if(action==='food'){cost=prices.food;home.food+=5;text='购买5份宠物粮，领养的每只宠物每天消耗1份。'}
  else if(action==='bed'||action==='toy'){if(home.facilities[action])return fail('已经购买这件设施了。');cost=prices[action];home.facilities[action]=true;text=action==='bed'?'柔软宠物窝已送到鼠鼠小屋。':'猫爬架与玩具已送到鼠鼠小屋。'}
  else if(action==='feed'){if(!home.pets.length)return fail('先领养宠物，再进行喂食。');if(selected.every(p=>p.fullness>=100))return fail('宠物已经吃饱了。');if(home.food<selected.length)return fail('宠物粮不足，请先补给。');home.food-=selected.length;selected.forEach(p=>p.fullness=Math.min(100,p.fullness+20));text=petId?'为'+selected[0].name+'喂了1份粮食。':'为每只宠物喂了1份粮食。'}
  else if(action==='pet'){if(!home.pets.length&&!(home.visitUntil>state.calendarTime))return fail('先领养宠物或购买一天陪伴体验。');const day=Math.floor(state.calendarTime/DAY);if(home.pettedDay===day)return fail('今天已经陪猫狗玩过了，明天再来吧。');home.pettedDay=day;state.mood=Math.min(100,state.mood+6);text='轻轻摸摸猫狗伙伴，心情增加6点。'}
  else return fail('没有这项宠物互动。');
  // Purchases are atomic: insufficient funds never grant animals, stock or facilities.
  if(state.seeds<cost)return {state:sim.migrate(structuredClone(input),time),ok:false,message:'瓜子不足，需要 '+cost+' 颗。'};state.seeds-=cost;if(!['follow','invite-npcs'].includes(action))sim.spendStamina(state,2);const entry={id:time+'-pet-'+action,time,calendarTime:state.calendarTime,type:'pet',mainId:state.mainId,text,place:'宠物之家'};state.events=[...state.events,entry].slice(-80);if(action.startsWith('adopt-'))state.notifications=[...state.notifications,entry].slice(-30);return {state,ok:true,message:text+(cost?' 花费'+cost+'颗瓜子。':'')};
 }
 function sceneEvent(state,detail,time=Date.now()){const home=normalize(state),npc=residents(state).find(n=>n.id===(detail.npcId||detail.id)),invite=home.invites.find(p=>p.npcId===npc?.id);if(!npc||!invite)return {state,ok:false};let text;if(detail.type==='pet-invited'){if(invite.status!=='pending')return {state,ok:false};invite.status='notified';npc.relationship=Math.min(100,(npc.relationship||0)+10);text=state.mainName+'告诉'+npc.name+'可以去宠物之家领养宠物，好感度增加10。'}else if(detail.type==='pet-npc-adopt'){if(invite.status!=='notified'||home.npcPets.some(p=>p.ownerId===npc.id)||home.npcPets.filter(p=>residents(state).some(n=>n.id===p.ownerId)).length>=5)return {state,ok:false};const pet=home.stock.shift();home.npcPets.push({...pet,adoptedSlot:0,ownerId:npc.id,adoptedAt:state.calendarTime,fullness:100});restock(home);invite.status='adopted';text=npc.name+'在宠物之家领养了'+pet.kind+'伙伴'+pet.name+'。'}else return {state,ok:false};const entry={id:time+'-'+detail.type+'-'+npc.id,time,calendarTime:state.calendarTime,type:'pet',text,place:'宠物之家'};state.events=[...state.events,entry].slice(-80);state.notifications=[...state.notifications,entry].slice(-30);return {state,ok:true,message:text}}
 return {normalize,recordIncome,adoptionPrice,settle,perform,candidates,prices,species,shopOwner,sceneEvent};
});
