(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.TownPets=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
 const DAY=86400000,candidates=[{id:'cat',name:'蜜桃',kind:'猫'},{id:'dog',name:'奶糖',kind:'狗'}],prices={visit:3,food:5,bed:8,toy:4};
 function normalize(state){const old=state.petHome||{};state.petHome={pets:[],food:0,follow:false,facilities:{bed:false,toy:false},income:[],incomeSince:state.calendarTime,...old,pets:(old.pets||[]).map(p=>({...p})),facilities:{bed:false,toy:false,...old.facilities},income:(old.income||[]).map(e=>({...e}))};return state.petHome}
 function recordIncome(state,amount){const home=normalize(state),day=Math.floor(state.calendarTime/DAY);if(amount<=0)return;const entry=home.income.find(e=>e.day===day);if(entry)entry.amount+=amount;else home.income.push({day,amount});home.income=home.income.filter(e=>e.day>=day-7)}
 function adoptionPrice(state){const home=state.petHome||normalize(state),day=Math.floor(state.calendarTime/DAY),entries=home.income.filter(e=>e.day>=day-6&&e.day<=day),days=Math.min(7,Math.max(1,day-Math.floor(home.incomeSince/DAY)+1));const average=entries.length?entries.reduce((sum,e)=>sum+e.amount,0)/days:10;return {average,cost:Math.max(1,Math.ceil(average*.5)),days}}
 function settle(state,from,to,time=Date.now()){const home=normalize(state),days=Math.max(0,Math.floor(to/DAY)-Math.floor(from/DAY));if(!days||!home.pets.length)return;for(let day=0;day<days;day++)for(const pet of home.pets){const fed=home.food>0;if(fed)home.food--;pet.fullness=Math.max(0,Math.min(100,(pet.fullness??80)+(fed?20:-20)))}if(home.food===0&&home.lastFoodNotice!==Math.floor(to/DAY)){home.lastFoodNotice=Math.floor(to/DAY);const e={id:'pet-food-'+to,time,calendarTime:to,type:'pet',place:'鼠鼠小屋',text:'鼠鼠小屋：宠物粮用完了，请及时补给照顾猫狗伙伴。'};state.notifications=[...(state.notifications||[]),e].slice(-30)}}
 function perform(input,action,{consent=false,time=Date.now(),petId}={}){const sim=typeof module==='object'&&module.exports?require('./town-sim.js'):globalThis.TownSimulation,state=sim.migrate(structuredClone(input),time),home=normalize(state),fail=message=>({state,ok:false,message});if(!state.alive)return fail('请先选择新的主鼠。');if(sim.mainSleeping(state))return sim.sleepBlocked(state);
  const selected=petId?home.pets.filter(p=>p.id===petId):home.pets;if(petId&&!selected.length)return fail('这只宠物尚未领养。');let cost=0,text='';
  if(action.startsWith('adopt-')){const pet=candidates.find(p=>p.id===action.slice(6));if(!pet)return fail('没有这只待领养的宠物。');if(home.pets.some(p=>p.id===pet.id))return fail('这只宠物已经是小镇的伙伴了。');if(!consent)return fail('请先确认会持续照顾宠物，领养后不提供弃养。');cost=adoptionPrice(state).cost;if(state.seeds<cost)return fail('瓜子不足，领养需要 '+cost+' 颗。');home.pets.push({...pet,adoptedAt:state.calendarTime,fullness:80});home.follow=true;text=state.mainName+'领养了'+pet.kind+'伙伴'+pet.name+'，它会跟随主鼠，回小屋生活。'}
  else if(action==='follow'){if(!home.pets.length)return fail('先领养宠物，再选择跟随。');home.follow=!home.follow;text=home.follow?'宠物开始跟随主鼠。':'宠物会回鼠鼠小屋等待。'}
  else if(action==='visit'){if(home.visitUntil>state.calendarTime)return fail('今天的陪伴体验仍在有效期内。');cost=prices.visit;home.visitUntil=state.calendarTime+DAY;text='开启一天猫狗陪伴体验，可在陪伴区与宠物互动。'}
  else if(action==='food'){cost=prices.food;home.food+=5;text='购买5份宠物粮，领养的每只宠物每天消耗1份。'}
  else if(action==='bed'||action==='toy'){if(home.facilities[action])return fail('已经购买这件设施了。');cost=prices[action];home.facilities[action]=true;text=action==='bed'?'柔软宠物窝已送到鼠鼠小屋。':'猫爬架与玩具已送到鼠鼠小屋。'}
  else if(action==='feed'){if(!home.pets.length)return fail('先领养宠物，再进行喂食。');if(selected.every(p=>p.fullness>=100))return fail('宠物已经吃饱了。');if(home.food<selected.length)return fail('宠物粮不足，请先补给。');home.food-=selected.length;selected.forEach(p=>p.fullness=Math.min(100,p.fullness+20));text=petId?'为'+selected[0].name+'喂了1份粮食。':'为每只宠物喂了1份粮食。'}
  else if(action==='pet'){if(!home.pets.length&&!(home.visitUntil>state.calendarTime))return fail('先领养宠物或购买一天陪伴体验。');const day=Math.floor(state.calendarTime/DAY);if(home.pettedDay===day)return fail('今天已经陪猫狗玩过了，明天再来吧。');home.pettedDay=day;state.mood=Math.min(100,state.mood+6);text='轻轻摸摸猫狗伙伴，心情增加6点。'}
  else return fail('没有这项宠物互动。');
  // Purchases are atomic: insufficient funds never grant animals, stock or facilities.
  if(state.seeds<cost)return {state:sim.migrate(structuredClone(input),time),ok:false,message:'瓜子不足，需要 '+cost+' 颗。'};state.seeds-=cost;if(action!=='follow')sim.spendStamina(state,2);const entry={id:time+'-pet-'+action,time,calendarTime:state.calendarTime,type:'pet',mainId:state.mainId,text,place:'宠物之家'};state.events=[...state.events,entry].slice(-80);if(action.startsWith('adopt-'))state.notifications=[...state.notifications,entry].slice(-30);return {state,ok:true,message:text+(cost?' 花费'+cost+'颗瓜子。':'')};
 }
 return {normalize,recordIncome,adoptionPrice,settle,perform,candidates,prices};
});
