import * as THREE from 'three';
import {lampLayout} from './town-lights.js';
import {createTownVerges} from './town-verges.js';
import {movePlayer} from './town-player.js';
import {createTownLife,destinations,facing,entrance} from './town-life.js';
import {createCottage} from './town-cottage.js';
import {createGarden,createPlaza,createSchool,createWheelPark,createSnackShop,createRestaurant,createClinic,createRemembranceHouse,createCemetery,birthdayHat} from './town-grounds.js';
import { clone } from 'three/examples/jsm/utils/SkeletonUtils.js';
import { FBXLoader } from 'three/examples/jsm/loaders/FBXLoader.js';

const places = [
  ['跑轮公园', -6, -5, 0x91b7a4, '夜里最热闹的运动场'],
  ['诊所', 0, -5, 0xb7c9d9, '医生鼠鼠守护大家的健康'],
  ['零食铺', 6, -5, 0xe4bd8f, '购买粮食和偶尔的小零食'],
  ['中心广场', 0, -1.3, 0xc9b6d8, '鼠鼠们碰面和交换消息的地方'],
  ['纪念馆', -6, 2.3, 0xa9a2b7, '收藏逝去鼠鼠的纪念物'],
  ['鼠鼠小屋', 0, 2.3, 0xd39b78, '休息、粮仓和家具都在这里'],
  ['小菜园', 6, 2.3, 0x88b779, '种下鼠鼠喜欢的新鲜食物'],
  ['殡仪馆', -2.1, 5.9, 0x8f91a4, '温柔送别小镇里的鼠鼠'],
  ['墓地', 2.8, 5.9, 0x778b83, '安静纪念每一段小小生命'],
  ['鼠鼠学校',9,8,0xd4ad75,'钟楼、教室和学习庭院'],
  ['鼠鼠饭馆',9,2,0xc5b69c,'厨房、柜台和舒适的用餐区']
];

places.forEach(p=>{const d=destinations.find(d=>d[0]===p[0]);p[1]=d[1];p[2]=d[2]});

function roundedBuilding(name, x, z, color) {
  if(name==='鼠鼠饭馆'){const model=createRestaurant();model.position.set(x,0,z);model.traverse(o=>o.userData.place=name);return model}
  if(name==='墓地'){const model=createCemetery();model.position.set(x,0,z);model.traverse(o=>o.userData.place=name);return model}
  if(name==='纪念馆'||name==='殡仪馆'){const model=createRemembranceHouse(name==='纪念馆');model.position.set(x,0,z);model.traverse(o=>o.userData.place=name);return model}
  if(name==='零食铺'||name==='诊所'){const model=name==='零食铺'?createSnackShop():createClinic();model.position.set(x,0,z);model.traverse(o=>o.userData.place=name);return model}
  if(['中心广场','小菜园','鼠鼠学校','跑轮公园'].includes(name)){const model=name==='中心广场'?createPlaza():name==='小菜园'?createGarden():name==='跑轮公园'?createWheelPark():createSchool();model.position.set(x,0,z);model.traverse(o=>o.userData.place=name);return model}
  if(name==='鼠鼠小屋'){const cottage=createCottage({density:.25});cottage.scale.setScalar(.8);cottage.position.set(x,0,z);cottage.traverse(o=>o.userData.place=name);return cottage}
  const group = new THREE.Group(); group.position.set(x, 0, z); group.userData.place = name;
  const body = new THREE.Mesh(new THREE.BoxGeometry(name === '中心广场' ? 2.3 : 2.5, .85, 1.65), new THREE.MeshStandardMaterial({color, roughness:.82}));
  body.position.y=.55; body.castShadow=true; body.receiveShadow=true; group.add(body);
  if(name === '中心广场') {
    body.geometry.dispose(); body.geometry = new THREE.CylinderGeometry(1.35,1.55,.3,32); body.position.y=.2;
    const fountain = new THREE.Mesh(new THREE.CylinderGeometry(.45,.62,.45,24),new THREE.MeshStandardMaterial({color:0xe9eef0,roughness:.65})); fountain.position.y=.55; group.add(fountain);
  } else {
    const roof = new THREE.Mesh(new THREE.ConeGeometry(1.75,.8,4),new THREE.MeshStandardMaterial({color:new THREE.Color(color).multiplyScalar(.76),roughness:.9})); roof.rotation.y=Math.PI/4;roof.position.y=1.35;roof.castShadow=true;group.add(roof);
    const door = new THREE.Mesh(new THREE.BoxGeometry(.48,.62,.05),new THREE.MeshStandardMaterial({color:0x74594c}));door.position.set(0,.38,-.85);group.add(door);
  }
  const box=(w,h,d,px,py,pz,tone)=>{const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color:tone,roughness:.85}));mesh.position.set(px,py,pz);mesh.castShadow=true;group.add(mesh);return mesh};
  if(!['中心广场','跑轮公园','小菜园','墓地'].includes(name)){
    box(2.8,.15,2,0,.06,0,0xc4b49d);
    [-.78,.78].forEach(x=>{box(.55,.48,.08,x,.66,.86,0xece2ba);box(.04,.49,.1,x,.66,.91,0x795c43);box(.56,.04,.1,x,.66,.91,0x795c43)});
    box(.52,.72,.09,0,.4,.88,0x765840);box(.8,.12,.42,0,.08,1.04,0xb2a18a);
    for(let y=.23;y<.98;y+=.18)box(2.52,.025,1.67,0,y,0,0xa4937c);
  }
  if(name==='诊所'){box(.18,.65,.12,0,1.25,1,0x528c79);box(.6,.18,.12,0,1.25,1,0x528c79)}
  if(name==='零食铺'){for(let i=0;i<8;i++)box(.34,.1,.85,-1.2+i*.34,1.02,1.08,i%2?0xf4e6c9:0xb97753);box(2.3,.35,.55,0,.25,1.25,0x906c4a);for(let i=0;i<5;i++)box(.3,.15,.32,-.85+i*.42,.5,1.25,0xd8b355)}
  if(name==='鼠鼠小屋'){box(.32,.9,.35,.75,1.5,-.25,0x9a6a50);box(1,.12,.5,-1.5,.12,.3,0xba9167)}
  if(name==='纪念馆'){[-1,-.5,.5,1].forEach(x=>box(.14,1.1,.18,x,.6,1,0xe2d9c7));box(2.8,.18,.45,0,1.15,1,0xc8bca7)}
  if(name==='殡仪馆'){box(2.7,.14,.7,0,1.03,1,0x6c7773);[-1,1].forEach(x=>box(.12,.9,.12,x,.5,1.25,0xaaa99c))}
  if(['跑轮公园','小菜园','墓地'].includes(name)){
    while(group.children.length){group.remove(group.children[0])}
    box(3,.12,2.2,0,.02,0,name==='小菜园'?0x6c543c:0xaab692);
    for(let x=-1.5;x<=1.5;x+=.3)box(.06,.5,.06,x,.25,-1.12,0xe0d1af);
    box(3,.07,.07,0,.35,-1.12,0xc7b393);
  }
  if(name==='跑轮公园'){
    const wheel=new THREE.Mesh(new THREE.TorusGeometry(.82,.1,12,48),new THREE.MeshStandardMaterial({color:0x8d6950}));wheel.position.y=1;group.add(wheel);
    for(let i=0;i<12;i++){const spoke=box(.04,1.6,.06,0,1,0,0xb39a73);spoke.rotation.z=i*Math.PI/6}box(1.5,.15,.9,0,.18,0,0x756750);
  }
  if(name==='小菜园'){for(let x=-1;x<=1;x+=.65){box(.42,.13,1.6,x,.16,0,0x513a29);for(let z=-.65;z<=.65;z+=.4){const leaf=new THREE.Mesh(new THREE.SphereGeometry(.18,10,8),new THREE.MeshStandardMaterial({color:0x5b8848}));leaf.scale.y=.55;leaf.position.set(x,.3,z);group.add(leaf)}}}
  if(name==='墓地'){for(let x=-.9;x<=.9;x+=.9){box(.48,.55,.16,x,.32,0,0xb9bdb5);box(.64,.09,.6,x,.12,.2,0xc8c9bd)}}
  group.traverse(o=>o.userData.place=name); return group;
}

const hamsterAsset=new FBXLoader().loadAsync('../assets/models/booth-hamster/restored/Assets/Ham/Mesh/Ham.fbx');
hamsterAsset.catch(()=>{});
function hamster(tone=0x9b9d98) {
  const rig=new THREE.Group();
  const texture=new THREE.TextureLoader().load('../assets/models/booth-hamster/restored/Assets/Ham/Texture/Ham.png');
  texture.colorSpace=THREE.SRGBColorSpace;
  const fur=new THREE.MeshStandardMaterial({map:texture,color:tone,roughness:.94});
  const eye=new THREE.MeshPhysicalMaterial({color:0x080706,roughness:.08,clearcoat:1});
  const whisker=new THREE.MeshStandardMaterial({color:0xd8d4cc,transparent:true,opacity:.78,side:THREE.DoubleSide});
  hamsterAsset.then(asset=>{
    const model=clone(asset),joints=[],bones={};
    model.traverse(child=>{if(child.isBone){const name=child.name.startsWith('mixamorig')&&!child.name.startsWith('mixamorig:')?child.name.replace(/^mixamorig/,'mixamorig:'):child.name;bones[name]={bone:child,base:child.quaternion.clone()};if(/Arm|Leg|Hand|Foot/.test(name))joints.push(bones[name])}if(!child.isMesh)return;child.castShadow=true;child.receiveShadow=true;
      const material=original=>{const name=(child.name+' '+(original?.name||'')).toLowerCase();return name.includes('eye')?eye:name.includes('hige')||name.includes('whisk')?whisker:fur};
      child.material=Array.isArray(child.material)?child.material.map(material):material(child.material);
    });
    const box=new THREE.Box3().setFromObject(model),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),scale=.62/Math.max(size.x,size.y,size.z);
    model.scale.setScalar(scale);model.position.set(-center.x*scale,-box.min.y*scale,-center.z*scale);rig.add(model);
    model.updateMatrixWorld(true);
    const tuckShoulder=(armName,foreArmName)=>{const arm=bones[armName],foreArm=bones[foreArmName];if(!arm||!foreArm||!arm.bone.parent)return;const shoulder=model.worldToLocal(arm.bone.getWorldPosition(new THREE.Vector3())),chest=new THREE.Vector3(shoulder.x*.72,shoulder.y-size.y*.16,shoulder.z+size.z*.035),target=arm.bone.parent.worldToLocal(model.localToWorld(chest)),current=foreArm.bone.position.clone().normalize().applyQuaternion(arm.base),desired=target.sub(arm.bone.position).normalize(),correction=new THREE.Quaternion().setFromUnitVectors(current,desired);arm.base=correction.multiply(arm.base.clone());arm.bone.quaternion.copy(arm.base)};
    tuckShoulder('mixamorig:LeftArm','mixamorig:LeftForeArm');tuckShoulder('mixamorig:RightArm','mixamorig:RightForeArm');model.updateMatrixWorld(true);
    const tuckForearm=(foreArmName,handName)=>{const foreArm=bones[foreArmName],hand=bones[handName];if(!foreArm||!hand||!foreArm.bone.parent)return;const elbow=model.worldToLocal(foreArm.bone.getWorldPosition(new THREE.Vector3())),side=Math.sign(elbow.x)||(foreArmName.includes('Left')?1:-1),paw=new THREE.Vector3(side*size.x*.105,center.y+size.y*.035,box.max.z+size.z*.035),target=foreArm.bone.parent.worldToLocal(model.localToWorld(paw)),current=hand.bone.position.clone().normalize().applyQuaternion(foreArm.base),desired=target.sub(foreArm.bone.position).normalize(),correction=new THREE.Quaternion().setFromUnitVectors(current,desired);foreArm.base=correction.multiply(foreArm.base.clone());foreArm.bone.quaternion.copy(foreArm.base)};
    tuckForearm('mixamorig:LeftForeArm','mixamorig:LeftHand');tuckForearm('mixamorig:RightForeArm','mixamorig:RightHand');model.updateMatrixWorld(true);
    const leftHand=bones['mixamorig:LeftHand']?.bone,rightHand=bones['mixamorig:RightHand']?.bone,forepawSpan=leftHand&&rightHand?leftHand.getWorldPosition(new THREE.Vector3()).distanceTo(rightHand.getWorldPosition(new THREE.Vector3())):null;
    rig.userData.joints=joints;rig.userData.bones=bones;rig.userData.model=model;rig.userData.modelBase=model.rotation.clone();rig.userData.armTucked=true;rig.userData.forepawSpan=forepawSpan;rig.userData.loaded=true;
    document.querySelector('#townScene').dataset.model='loaded';
  }).catch(()=>{document.querySelector('#townActivity').textContent='鼠鼠模型加载失败，请返回后重新进入。'});
  return rig;
}

function init() {
  const host=document.querySelector('#townScene'),canvas=host?.querySelector('canvas'); if(!host||!canvas)return;
  const scene=new THREE.Scene(); scene.background=new THREE.Color(0xdce9df); scene.fog=new THREE.Fog(0xdce9df,45,85);
  const camera=new THREE.PerspectiveCamera(38,1,.1,100); camera.position.set(13,15,17);camera.lookAt(0,0,1);
  const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
  const ambient=new THREE.HemisphereLight(0xfff4df,0x66766d,2.4);scene.add(ambient);const sun=new THREE.DirectionalLight(0xffe4bd,3.1);sun.position.set(-8,15,-7);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(sun);
  const ground=new THREE.Mesh(new THREE.CylinderGeometry(18,18.5,.65,64),new THREE.MeshStandardMaterial({color:0x9fbd91,roughness:1}));ground.position.y=-.35;ground.receiveShadow=true;scene.add(ground);
  const pathMat=new THREE.MeshStandardMaterial({color:0xd9c9ad,roughness:1});
  const road=(x,z,w,d,angle=0)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(w,.035,d),pathMat);m.position.set(x,.01,z);m.rotation.y=angle;m.receiveShadow=true;scene.add(m)};
  road(0,-1.3,28,1.05);road(0,.1,1.05,25.2);
  places.filter(p=>p[0]!=='中心广场').forEach(p=>{const e=entrance(p[0]),near=Math.abs(e.x)<Math.abs(e.z+1.3)?{x:0,z:e.z}:{x:e.x,z:-1.3},dx=e.x-near.x,dz=e.z-near.z,len=Math.hypot(dx,dz);if(len>.1)road((e.x+near.x)/2,(e.z+near.z)/2,.75,len,Math.atan2(dx,dz))});
  const streetLights=new THREE.Group(),lampBulbs=[],lampPositions=[],poolCanvas=document.createElement('canvas');poolCanvas.width=poolCanvas.height=128;const poolContext=poolCanvas.getContext('2d'),poolGradient=poolContext.createRadialGradient(64,64,4,64,64,64);poolGradient.addColorStop(0,'rgba(255,224,158,.9)');poolGradient.addColorStop(.38,'rgba(255,213,128,.48)');poolGradient.addColorStop(1,'rgba(255,205,110,0)');poolContext.fillStyle=poolGradient;poolContext.fillRect(0,0,128,128);const poolTexture=new THREE.CanvasTexture(poolCanvas);poolTexture.colorSpace=THREE.SRGBColorSpace;
  function streetLamp(x,z,yaw){const lamp=new THREE.Group(),metal=new THREE.MeshStandardMaterial({color:0x303633,roughness:.76}),shade=new THREE.MeshStandardMaterial({color:0x4d5349,roughness:.72}),bulbMaterial=new THREE.MeshStandardMaterial({color:0xffe3a4,emissive:0xffc766,emissiveIntensity:0});const pole=new THREE.Mesh(new THREE.CylinderGeometry(.045,.065,1.65,10),metal);pole.position.y=.83;const arm=new THREE.Mesh(new THREE.BoxGeometry(.48,.055,.055),metal);arm.position.set(.2,1.61,0);const cap=new THREE.Mesh(new THREE.ConeGeometry(.22,.2,16),shade);cap.position.set(.41,1.49,0);cap.rotation.z=Math.PI;const bulb=new THREE.Mesh(new THREE.SphereGeometry(.105,14,10),bulbMaterial);bulb.position.set(.41,1.42,0);const light=new THREE.PointLight(0xffc978,0,4.8,2);light.position.copy(bulb.position);const pool=new THREE.Mesh(new THREE.CircleGeometry(2.05,32),new THREE.MeshBasicMaterial({map:poolTexture,color:0xffe0a0,transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending}));pool.rotation.x=-Math.PI/2;pool.position.set(.41,.025,0);lamp.add(pole,arm,cap,bulb,light,pool);lamp.position.set(x,0,z);lamp.rotation.y=yaw;streetLights.add(lamp);lampBulbs.push({material:bulbMaterial,light,pool});lampPositions.push([x,z])}
  lampLayout().forEach(({x,z,yaw})=>streetLamp(x,z,yaw));scene.add(streetLights);scene.add(createTownVerges());
  const clickable=[],placeModels=new Map();places.forEach(place=>{const obj=roundedBuilding(...place);obj.rotation.y=facing(place[0]);placeModels.set(place[0],obj);clickable.push(obj);scene.add(obj)});
  const pet=hamster();pet.userData.mainPet=true;scene.add(pet);clickable.push(pet);
  const roles=['跑轮管理员','医生','零食店主','广场邻居','纪念馆管理员','小屋邻居','园丁','礼仪师','守墓人'];
  const residents=places.slice(0,9).map(([place,x,z],i)=>{
    const npc=hamster([0xbba58a,0xc8c8bb,0xa49782][i%3]);npc.userData.npcIndex=i;npc.traverse(child=>child.userData.npcIndex=i);scene.add(npc);clickable.push(npc);
    const tag=document.createElement('button');tag.className='town-label town-npc-label';tag.hidden=true;tag.textContent=roles[i];host.appendChild(tag);
    tag.onclick=()=>focusResident(i);
    return {rig:npc,x:x+(place==='中心广场'?1.9:0),z:z+1.7,phase:i*1.8,tag};
  });
  const gaitRotation=new THREE.Quaternion(),gaitEuler=new THREE.Euler();
  function poseBone(rig,name,x=0,y=0,z=0){const joint=rig.userData.bones?.[`mixamorig:${name}`];if(!joint)return;joint.bone.quaternion.copy(joint.base).multiply(gaitRotation.setFromEuler(gaitEuler.set(x,y,z)))}
  function walk(rig,time,phase,x,z,actor=null){
    const cycle=(time+phase)%14,travel=9.5,raw=Math.min(cycle,travel)/travel,eased=raw*raw*(3-2*raw),progress=eased*Math.PI*2,moving=actor?actor.moving:cycle<travel,blend=moving?(actor?1:Math.min(1,Math.sin(raw*Math.PI)*4)):0;
    rig.position.set(actor?x:x+Math.sin(progress)*.55,.035,actor?z:z+Math.cos(progress)*.22);
    if(actor)rig.rotation.y=actor.heading;else if(moving&&blend>.03)rig.rotation.y=Math.atan2(.55*Math.cos(progress),-.22*Math.sin(progress));
    const step=actor?time*8:progress*5.5;const frontLeft=Math.sin(step)*blend,frontRight=-frontLeft,hindLeft=frontRight,hindRight=frontLeft;
    const lift=value=>Math.max(0,value),plant=value=>Math.max(0,-value);
    rig.position.y+=Math.abs(Math.sin(step*2))*.012*blend;
    const model=rig.userData.model;if(model){const base=rig.userData.modelBase;model.rotation.set(base.x+.035*blend,base.y,base.z+Math.sin(step)*.025*blend)}
    poseBone(rig,'LeftArm',frontLeft*.48-.08*blend,0,-.05*blend);poseBone(rig,'RightArm',frontRight*.48-.08*blend,0,.05*blend);
    poseBone(rig,'LeftForeArm',-.12*blend-lift(frontLeft)*.58+plant(frontLeft)*.1);poseBone(rig,'RightForeArm',-.12*blend-lift(frontRight)*.58+plant(frontRight)*.1);
    poseBone(rig,'LeftHand',lift(frontLeft)*.34);poseBone(rig,'RightHand',lift(frontRight)*.34);
    poseBone(rig,'LeftUpLeg',hindLeft*.55+.1*blend);poseBone(rig,'RightUpLeg',hindRight*.55+.1*blend);
    poseBone(rig,'LeftLeg',lift(hindLeft)*.68-plant(hindLeft)*.12);poseBone(rig,'RightLeg',lift(hindRight)*.68-plant(hindRight)*.12);
    poseBone(rig,'LeftFoot',-lift(hindLeft)*.42);poseBone(rig,'RightFoot',-lift(hindRight)*.42);
    poseBone(rig,'Spine',0,0,-Math.sin(step)*.035*blend);poseBone(rig,'Spine1',0,0,-Math.sin(step)*.025*blend);poseBone(rig,'Neck',-.035*blend,0,Math.sin(step)*.025*blend);poseBone(rig,'Head',-.035*blend,0,Math.sin(step)*.035*blend);
    rig.userData.gaitSample={moving,blend:Number(blend.toFixed(2)),frontLeft:Number(frontLeft.toFixed(2)),hindLeft:Number(hindLeft.toFixed(2)),lift:Number(Math.max(lift(frontLeft),lift(frontRight),lift(hindLeft),lift(hindRight)).toFixed(2))};
  }
  const labels=places.map(([name,x,z])=>{const button=document.createElement('button');button.className='town-label';button.textContent=name;button.onclick=()=>enterPlace(name);host.appendChild(button);return {button,point:new THREE.Vector3(x,name==='中心广场'?1.85:name==='鼠鼠学校'?4.4:2.1,z)}});
  const landscape=new THREE.Mesh(new THREE.PlaneGeometry(160,160),new THREE.MeshStandardMaterial({color:0x92ad7e,roughness:1}));landscape.rotation.x=-Math.PI/2;landscape.position.y=-.7;scene.add(landscape);
  for(let i=0;i<34;i++){const tree=new THREE.Group(),trunk=new THREE.Mesh(new THREE.CylinderGeometry(.08,.11,.55,8),new THREE.MeshStandardMaterial({color:0x80644d})),leaf=new THREE.Mesh(new THREE.SphereGeometry(.34,12,9),new THREE.MeshStandardMaterial({color:i%3?0x5f946a:0x7ca56e,roughness:1}));trunk.position.y=.28;leaf.position.y=.73;tree.add(trunk,leaf);const a=i/34*Math.PI*2,r=17.1;tree.position.set(Math.cos(a)*r,0,Math.sin(a)*r);scene.add(tree)}
  let yaw=0,pitch=.83,distance=34,drag=null,activePlace=null,savedCamera=null,focusedResident=-1,focusedPup=null,savedFocusCamera=null,worldState={};let hoverPointer=null,hoveredActor=null,hoverUntil=0;let firstPerson=false,playerYaw=0,playerPitch=0,playerSavedCamera=null,jumpHeight=0,jumpVelocity=0;const playerKeys=new Set();
  const target=new THREE.Vector3(0,0,1);
  const room=new THREE.Group();room.visible=false;scene.add(room);
  const weatherFx=new THREE.Group();scene.add(weatherFx);
  const roomLabels=[],pups=new Map();
  const life=createTownLife(detail=>queueMicrotask(()=>window.dispatchEvent(new CustomEvent('town-life-event',{detail}))));
  const mainTag=document.createElement('button');mainTag.className='town-label town-npc-label town-pup-label';mainTag.onclick=()=>focusPet();host.appendChild(mainTag);
  const lifeBubbles=new Map();
  function syncLife(){const ids=new Set();if(worldState.alive!==false||worldState.pendingFarewell?.phase==='resting'){ids.add('main');const a=life.add('main','鼠鼠小屋',{name:'鼠鼠'});a.allowSocial=worldState.socialAllowed!==false;a.frozen=worldState.alive===false;if(a.frozen){a.inside='鼠鼠小屋';a.position={x:-2.2,z:-.7};a.phase='activity';a.action='休息';a.speech='';a.moving=false}}residents.forEach((resident,i)=>{const data=worldState.npcs?.[i];if(data?.alive===false)return;const id=data?.id||'npc-'+i;resident.lifeId=id;ids.add(id);const a=life.add(id,places[i][0],{name:data?.name||roles[i]});a.allowSocial=(worldState.npcSocialCounts?.[id]||0)<6});pups.forEach(item=>{ids.add(item.data.id);const a=life.add(item.data.id,'鼠鼠小屋',{name:item.data.name,child:true,age:item.data.ageYears});a.age=item.data.ageYears});for(const id of life.actors.keys())if(!ids.has(id)){life.remove(id);lifeBubbles.get(id)?.remove();lifeBubbles.delete(id)}}
  function renderActor(rig,actor,t){if(!actor){rig.visible=false;return}const viewingInside=indoorNames.includes(activePlace);rig.visible=viewingInside?actor.inside===activePlace:!actor.inside;walk(rig,t,0,actor.position.x,actor.position.z,actor);let hat=rig.userData.birthdayHat;if(!hat){hat=birthdayHat();hat.position.y=.65;rig.add(hat);rig.userData.birthdayHat=hat}hat.visible=worldState.celebration?.birthdays?.includes(actor.id)||false;if(actor.phase==='celebrating'){poseBone(rig,'LeftForeArm',-.45-Math.sin(t*3)*.22);poseBone(rig,'RightForeArm',-.45+Math.sin(t*3)*.22);poseBone(rig,'Head',Math.sin(t*2)*.08)}if(actor.phase==='activity'&&rig.userData.model){if(actor.action==='检查')rig.position.y=.62;const resting=['休息','睡觉'].includes(actor.action);if(resting){rig.userData.model.rotation.z=.75;rig.position.y=actor.action==='睡觉'&&actor.inside==='鼠鼠小屋'?.65:.12}else{poseBone(rig,'Head',.22+Math.sin(t*3)*.06);poseBone(rig,'LeftForeArm',-.45+Math.sin(t*4)*.12);poseBone(rig,'RightForeArm',-.45-Math.sin(t*4)*.12);if(actor.action==='学习'){poseBone(rig,'Head',.32+Math.sin(t*1.5)*.025);poseBone(rig,'LeftForeArm',-.65);poseBone(rig,'RightForeArm',-.65+Math.sin(t*2)*.12)}else if(actor.action==='纪念'){poseBone(rig,'Head',.3);poseBone(rig,'LeftForeArm',-.2);poseBone(rig,'RightForeArm',-.2)}else if(actor.action==='工作'){poseBone(rig,'Head',.18);poseBone(rig,'LeftForeArm',-.55+Math.sin(t*2)*.18);poseBone(rig,'RightForeArm',-.55-Math.sin(t*2)*.18)}if(actor.action==='跑轮'){poseBone(rig,'LeftUpLeg',Math.sin(t*10)*.6);poseBone(rig,'RightUpLeg',-Math.sin(t*10)*.6)}}}if(actor.phase==='talking'){poseBone(rig,'Head',Math.sin(t*2)*.07,Math.sin(t)*.05,0);poseBone(rig,'LeftForeArm',-.22-Math.max(0,Math.sin(t*3))*.3)}let bubble=lifeBubbles.get(actor.id);if(!bubble){bubble=document.createElement('div');bubble.className='town-label town-life-bubble';bubble.dataset.actorId=actor.id;host.appendChild(bubble);lifeBubbles.set(actor.id,bubble)}bubble.textContent=actor.speech;bubble.hidden=!rig.visible||!actor.speech||(firstPerson&&actor.id==='main')}

  const returnButton=document.createElement('button');returnButton.className='town-room-return';returnButton.textContent='← 返回小镇';returnButton.hidden=true;host.appendChild(returnButton);
  const speech=document.createElement('div');speech.className='town-npc-speech';speech.hidden=true;host.appendChild(speech);
  const indoorNames=['鼠鼠饭馆','鼠鼠小屋','诊所','零食铺','纪念馆','殡仪馆','鼠鼠学校'];
  function clearRoom(){for(let i=clickable.length-1;i>=0;i--)if(clickable[i].userData.roomAction)clickable.splice(i,1);roomLabels.splice(0).forEach(item=>item.button.remove());while(room.children.length){const child=room.children[0];child.traverse(o=>{if(o.isMesh){o.geometry.dispose();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material.dispose()}});room.remove(child)}}
  function buildRoom(name){
    clearRoom();
    const palettes={'鼠鼠饭馆':[0xbda988,0xeee8d9,0x655746],'鼠鼠小屋':[0xb58d62,0xe1c6a0,0x94704e],'诊所':[0xdbe6e7,0xf0f6f5,0x83b6c4],'零食铺':[0xd4bf94,0xf3e3b1,0xa8c3a3],'鼠鼠学校':[0xbd976a,0xe3cca2,0x987142],'纪念馆':[0xd4ccba,0xeee5ce,0xa6b397],'殡仪馆':[0xc8c5b9,0xeee5d1,0x8b9a9f]},[floorColor,wallColor,trimColor]=palettes[name];
    const add=(w,h,d,x,y,z,color)=>{const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:.8}));mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;room.add(mesh);return mesh};
    const label=(text,x,z,action)=>{const button=document.createElement(action?'button':'span');button.className='town-label town-furniture-label';button.textContent=text;if(action)button.onclick=()=>window.dispatchEvent(new CustomEvent('town-object-action',{detail:{action,place:name}}));host.appendChild(button);roomLabels.push({button,point:new THREE.Vector3(x,.95,z)})};
    add(8,.18,6,0,-.1,0,floorColor);add(8,1.9,.16,0,.85,-3,wallColor);const sideWall=add(.16,1.9,6,-4,.85,0,wallColor);if(name==='诊所'){sideWall.material.color.set(0xb9dce2);sideWall.material.transparent=true;sideWall.material.opacity=.3}add(8,.2,.16,0,0,3,trimColor);add(.16,.2,6,4,0,0,trimColor);
    const tiled=['诊所','纪念馆','殡仪馆'].includes(name);for(let x=-3.8;x<4;x+=tiled?.6:.4)add(.012,.01,6,x,0,0,trimColor);if(tiled)for(let z=-2.8;z<3;z+=.6)add(8,.01,.012,0,0,z,trimColor);
    add(8,.28,.03,0,.2,-2.9,trimColor);add(.03,.28,6,-3.9,.2,0,trimColor);
    const oval=(x,y,z,sx,sy,sz,color)=>{const mesh=new THREE.Mesh(new THREE.SphereGeometry(1,14,10),new THREE.MeshStandardMaterial({color,roughness:.8}));mesh.position.set(x,y,z);mesh.scale.set(sx,sy,sz);room.add(mesh);return mesh};
    const cylinder=(x,y,z,r,h,color)=>{const mesh=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,16),new THREE.MeshStandardMaterial({color,roughness:.7}));mesh.position.set(x,y,z);room.add(mesh);return mesh};
    const windowFrame=(x,z)=>{const shape=new THREE.Shape();shape.moveTo(-.38,0);shape.lineTo(.38,0);shape.lineTo(.38,.65);shape.absarc(0,.65,.38,0,Math.PI,false);shape.lineTo(-.38,0);const mesh=new THREE.Mesh(new THREE.ShapeGeometry(shape),new THREE.MeshStandardMaterial({color:0xa6c8cb,roughness:.3}));mesh.position.set(x,.62,z);room.add(mesh);for(const dx of [-.4,.4])add(.04,.7,.06,x+dx,.96,z+.02,trimColor);const arch=new THREE.Mesh(new THREE.TorusGeometry(.4,.025,8,24,Math.PI),new THREE.MeshStandardMaterial({color:trimColor}));arch.position.set(x,1.27,z+.02);room.add(arch);add(.025,.95,.04,x,1.1,z+.03,trimColor);add(.76,.025,.04,x,1.1,z+.03,trimColor);add(.86,.07,.16,x,.61,z+.04,trimColor)};
    for(const x of [-3,3])windowFrame(x,-2.89);
    const table=(x,z,w,d,color)=>{add(w,.09,d,x,.58,z,color);for(const dx of [-w*.38,w*.38])for(const dz of [-d*.36,d*.36])add(.07,.53,.07,x+dx,.27,z+dz,color)};
    const bench=(x,z)=>{table(x,z,2,.65,trimColor);add(2,.26,.065,x,.78,z-.28,trimColor);for(const dx of [-.8,.8])add(.055,.6,.055,x+dx,.54,z-.26,trimColor)};
    const bouquet=(x,y,z)=>{cylinder(x,y,z,.1,.22,wallColor);for(let i=0;i<7;i++){const a=i*2.4;oval(x+Math.cos(a)*.11,y+.24,z+Math.sin(a)*.11,.08,.08,.06,i%2?0xd2aaa2:0xe7d7ae);oval(x+Math.cos(a)*.1,y+.1,z+Math.sin(a)*.1,.08,.1,.04,0x809365)}};
    const bed=(x,z,text)=>{const clinical=name==='诊所';add(1.9,.3,1.2,x,.2,z,clinical?trimColor:0x886846);add(1.78,.18,1.1,x,.43,z,clinical?0xf0f4f0:0xe9dbba);add(.45,.17,.8,x-.58,.6,z,0xf7eed9);add(.9,.09,1.05,x+.3,.56,z,clinical?0xb6d2dc:0x879c8a);if(clinical){for(const end of [-1,1]){add(.08,.48,1.22,x+end*.92,.49,z,trimColor);for(const side of [-1,1]){oval(x+end*.76,.13,z+side*.43,.07,.07,.045,0x687b84);add(1.3,.035,.035,x,.76,z+side*.58,0xa4b7ba)}}}label(text,x,z)};
    const shelf=(x,z,text)=>{const color=name==='诊所'?trimColor:name==='零食铺'?0xa8c3a3:0x98744f;add(1.6,1.35,.18,x,.68,z-.22,color);[-.72,.72].forEach(dx=>add(.1,1.4,.6,x+dx,.7,z,color));[.12,.65,1.2].forEach(y=>{add(1.6,.08,.6,x,y,z,color);for(let i=0;i<4;i++){const px=x-.5+i*.33;if(name==='诊所'){cylinder(px,y+.15,z,.07,.23,0xe9f0ee);cylinder(px,y+.285,z,.055,.04,trimColor);add(.08,.06,.012,px,y+.17,z+.071,trimColor)}else if(name==='零食铺'||name==='鼠鼠小屋'){add(.29,.06,.38,px,y+.08,z,name==='零食铺'?0xe0a9a3:0xc6a576);for(let n=0;n<6;n++)oval(px+(n%3-1)*.07,y+.16,z+(Math.floor(n/3)-.5)*.11,.04,.045,.06,[0xc39958,0xa27648,0xd8b95c][i%3])}else if(name==='鼠鼠学校'){for(let n=0;n<3;n++)add(.065,.23+n*.025,.24,px+n*.075-.075,y+.15,z,[0x789187,0xb88166,0xc2aa69][n])}else{add(.22,.25,.25,px,y+.16,z,0xc7c49e)}}});label(text,x,z)};
    if(name==='鼠鼠小屋'){
      bed(-2.2,-1.6,'床铺');for(let i=0;i<13;i++)add(.018,1.5,.025,-3.6+i*.6,1,-2.88,0xc4a178);bouquet(-3.25,.12,1.9);
      const bowl=new THREE.Mesh(new THREE.TorusGeometry(.36,.1,12,32),new THREE.MeshStandardMaterial({color:0xe9d4b5}));bowl.rotation.x=Math.PI/2;bowl.position.set(1.8,.18,1.2);room.add(bowl);add(.5,.06,.5,1.8,.1,1.2,0x9a7944);label('食盆',1.8,1.2);
      add(.16,1.2,.16,1.7,.6,-1.2,0x8b7355);const bottle=new THREE.Mesh(new THREE.CylinderGeometry(.2,.2,.65,20),new THREE.MeshStandardMaterial({color:0xb0d5d8,transparent:true,opacity:.72}));bottle.position.set(1.7,.82,-1.2);room.add(bottle);bottle.userData.roomAction="water";clickable.push(bottle);add(.07,.3,.07,1.7,.36,-1.05,0xbbbfc1);const water=worldState.water||{amount:100,quality:'新鲜'},level=Math.max(.001,water.amount/100);const liquid=new THREE.Mesh(new THREE.CylinderGeometry(.17,.17,.61,20),new THREE.MeshStandardMaterial({color:water.quality==='变质'?0x858444:0x469ec4,transparent:true,opacity:.85}));liquid.scale.y=level;liquid.position.set(1.7,.505+.305*level,-1.2);room.add(liquid);const waterQuality=water.amount<=0?'缺水':water.quality,waterText={新鲜:'水质正常',待换水:'建议换水',变质:'水已变质',缺水:'水已耗尽'}[waterQuality];label(`水壶 ${Math.ceil(water.amount)}% · ${waterText}\n点击清洗换水`,1.7,-1.2,'water');const waterLabel=roomLabels.at(-1).button;waterLabel.classList.add('town-water-label');waterLabel.dataset.quality=waterQuality;waterLabel.title=`${waterText}，点击免费清洗并补满新鲜水。`;
      shelf(.2,-2.4,'粮仓');roomLabels.at(-1).button.remove();roomLabels.pop();label('粮仓 · 点击补给',.2,-2.4,'supply');const moved=worldState.furniture?.table?.slot==='window',tableX=moved?2.2:-2.3,tableZ=moved?-.8:1.1;table(tableX,tableZ,1,.75,0x9b7851);label('木桌',tableX,tableZ);add(.65,.15,.65,tableX+1,.1,tableZ+.2,0x92a082);label('坐垫',tableX+1,tableZ+.2);if(worldState.furniture?.lamp?.owned){add(.08,.65,.08,tableX,.9,tableZ,0x6f614c);const shade=new THREE.Mesh(new THREE.ConeGeometry(.28,.35,16),new THREE.MeshStandardMaterial({color:0xe4c66e,emissive:0x7b5e20,emissiveIntensity:.35}));shade.position.set(tableX,1.25,tableZ);room.add(shade);label('台灯',tableX,tableZ)}
    }else if(name==='诊所'){bed(-1.9,-.8,'诊疗床');shelf(1.6,-2.4,'药柜');add(1.4,.7,.8,1.9,.38,1.2,trimColor);add(1.5,.07,.87,1.9,.77,1.2,0xf0f5f2);label('检查台',1.9,1.2);add(.5,.36,.08,1.9,1.04,1,0xa3bac0);add(.42,.27,.015,1.9,1.05,1.05,0x3e626a);add(.8,.1,.025,0,1.4,-2.88,0xc65e59);add(.1,.8,.025,0,1.4,-2.88,0xc65e59);add(.025,1.5,.025,-2.9,.78,-1.1,0xa4b7ba);add(.4,.025,.025,-2.9,1.5,-1.1,0xa4b7ba);cylinder(-3,1.28,-1.1,.065,.25,0xe2eeee)}
    else if(name==='鼠鼠饭馆'){
      add(6.5,.8,.8,0,.4,-2.3,0x655746);add(6.6,.08,.9,0,.84,-2.3,0xc5bba5);label('厨房',0,-2.3);
      for(const x of [-2,0,2]){cylinder(x,.93,-2.3,.22,.12,0x424a48);cylinder(x,1.08,-2.3,.2,.16,0xc3a374);for(let i=0;i<5;i++)oval(x+Math.cos(i*1.3)*.1,1.17,-2.3+Math.sin(i*1.3)*.1,.055,.025,.04,0xd9bd79)}
      add(1.8,.85,.7,2.5,.42,.5,0x655746);add(1.9,.08,.8,2.5,.88,.5,0xbda988);label('点餐柜台',2.5,.5);
      for(const x of [-1.4,1])for(const z of [-.2,1.6]){table(x,z,1.3,.8,0x987954);for(const dz of [-.65,.65]){cylinder(x,.23,z+dz,.24,.4,0x826c51);cylinder(x,.45,z+dz,.27,.06,0xbda988)}cylinder(x,.66,z,.2,.035,0xeee8d9);for(let i=0;i<6;i++)oval(x+Math.cos(i)*.11,.7,z+Math.sin(i)*.11,.055,.04,.04,i%2?0x83a05c:0xd5ac66)}label('用餐区',-1.4,.5);
    }
    else if(name==='零食铺'){shelf(-2.2,-2.4,'粮食货架');shelf(.5,-2.4,'零食货架');add(3,.85,.85,.5,.43,1.3,0xa8c3a3);add(3.1,.09,.95,.5,.9,1.3,0xe0a9a3);label('柜台',.5,1.3);for(let i=0;i<5;i++){const x=-.6+i*.55;add(.43,.08,.5,x,.99,1.3,0xf3e3b1);for(let j=0;j<6;j++)oval(x+(j%3-1)*.1,1.08,1.3+(Math.floor(j/3)-.5)*.14,.065,.06,.075,i%2?0xd4a466:0xa66b48)}table(-2.7,1.1,.9,.6,0xa8c3a3);cylinder(-2.7,.65,1.1,.19,.025,0xf3e3b1);for(let i=0;i<8;i++)add(.85,.25,.03,-3.3+i*.9,1.65,-2.85,i%3===0?0xe0a9a3:i%3===1?0xa8c3a3:0xf3e3b1)}
    else if(name==='鼠鼠学校'){shelf(-2.6,-2.4,'书柜');roomLabels.at(-1).button.remove();roomLabels.pop();label('书柜',-2.6,-2.4,'school-books');const board=add(2.6,1.3,.1,.5,1,-2.65,0x385d48),c=document.createElement('canvas');c.width=512;c.height=256;const g=c.getContext('2d');g.fillStyle='#365d48';g.fillRect(0,0,512,256);g.fillStyle='#eee9d4';g.font='30px Microsoft YaHei';const text=worldState.schoolBoard||'欢迎来到鼠鼠学校';for(let i=0;i<text.length;i+=15)g.fillText(text.slice(i,i+15),22,43+Math.floor(i/15)*37);board.material.color.set(0xffffff);board.material.map=new THREE.CanvasTexture(c);board.material.map.colorSpace=THREE.SRGBColorSpace;label('黑板',.5,-2.5,'school-board');for(const x of [-1,1.4])for(const z of [-.6,1.1]){table(x,z,1.2,.7,0xb89058);add(.65,.07,.55,x,.32,z+.7,0xa47b49);for(const dx of [-.22,.22])add(.055,.3,.055,x+dx,.15,z+.7,0xa47b49);add(.65,.32,.05,x,.52,z+.95,0xa47b49);add(.4,.035,.28,x,.64,z,0xf2e8c9)}label('课桌',1.4,1.1,'school-desk')}
    else if(name==='纪念馆'){[-2.2,0,2.2].forEach((x,i)=>{add(1.4,.55,.8,x,.28,-1.4,trimColor);if(i===0){oval(x,.69,-1.4,.15,.12,.1,0xc4a16d);cylinder(x+.35,.65,-1.4,.09,.2,0xb5c5ba)}else{add(.65,.025,.44,x,.59,-1.4,0xe9dcc0);add(.24,.015,.29,x-.17,.61,-1.4,i===1?0xc9ba9a:0x9cafa2);add(.24,.015,.29,x+.17,.61,-1.4,0xf2e8d0)}const glass=add(1.4,.65,.8,x,.88,-1.4,0xdceae1);glass.material.transparent=true;glass.material.opacity=.16;glass.material.depthWrite=false;label(['纪念物展柜','生平卡片展柜','相册展柜'][i],x,-1.4)});bench(0,1.5);label('休息长椅',0,1.5);for(const x of [-3.35,3.35])bouquet(x,.22,1.4);for(let i=0;i<8;i++){const x=-1.4+(i%4)*.9,y=1.1+Math.floor(i/4)*.5;add(.3,.34,.025,x,y,-2.86,trimColor);oval(x,y,-2.84,.085,.1,.013,0xd9c69e)}}
    else{add(2.5,.65,1.2,0,.34,-1,trimColor);add(2.55,.045,1.23,0,.7,-1,0xe6ded0);label('告别台',0,-1);shelf(-2.6,-2.4,'送别用品柜');bench(0,1.4);label('等候长椅',0,1.4);for(const x of [-1,1]){cylinder(x,.8,-1,.075,.2,0xe8dbc0);oval(x,.93,-1,.025,.05,.025,0xe1b870)}for(const x of [-2,2])bouquet(x,.25,-.5);add(.58,.65,.045,0,1.25,-2.88,trimColor);add(.47,.54,.025,0,1.25,-2.85,0xded4bd)}
  }
  function enterPlace(name){
    clearFocus(false);
    if(activePlace)leavePlace();
    savedCamera={yaw,pitch,distance,target:target.clone()};activePlace=name;
    document.querySelector('#townPlace b').textContent=name;document.querySelector('#townPlace span').textContent=indoorNames.includes(name)?'屋顶剖视 · 拖动旋转 · 滚轮缩放':'近距离查看 · 拖动旋转 · 滚轮缩放';
    const indoor=indoorNames.includes(name);
    if(indoor){buildRoom(name);scene.children.forEach(child=>{if(!child.isLight&&child!==room)child.visible=false});room.visible=true;target.set(0,0,0);distance=13;pitch=.92;yaw=.18}
    else{const place=places.find(p=>p[0]===name);target.set(place[1],.2,place[2]);distance=name==='墓地'?6.2:8;pitch=name==='墓地'?1:.85;yaw=facing(name)+.2;if(name==='墓地'){document.querySelector('#townPlace span').textContent='园内俯视 · 大门朝向道路 · 拖动旋转 · 滚轮缩放';placeModels.forEach((model,key)=>model.visible=key==='墓地')}}
    syncPups();syncLife();returnButton.hidden=false;host.dataset.place=name;positionCamera();window.dispatchEvent(new CustomEvent('town-place-select',{detail:{place:name}}));
  }
  function leavePlace(){
    if(!activePlace)return;clearFocus(false);room.visible=false;clearRoom();scene.children.forEach(child=>{if(child!==room)child.visible=true});yaw=savedCamera.yaw;pitch=savedCamera.pitch;distance=savedCamera.distance;target.copy(savedCamera.target);activePlace=null;savedCamera=null;returnButton.hidden=true;delete host.dataset.place;applyWorld(worldState);positionCamera();document.querySelector('#townPlace b').textContent='中心广场';document.querySelector('#townPlace span').textContent='鼠鼠们碰面和交换消息的地方';window.dispatchEvent(new CustomEvent('town-view-close'));
  }
  function focusResident(index){
    const npc=residents[index];if(!npc?.rig.visible)return;if(focusedResident===-1)savedFocusCamera={yaw,pitch,distance,target:target.clone()};focusedResident=index;target.copy(npc.rig.position).add(new THREE.Vector3(1.05,.25,0));yaw=.15;pitch=.68;distance=5.4;returnButton.hidden=false;host.dataset.resident=String(index);document.querySelector('#townPlace b').textContent=worldState.npcs?.[index]?.name||roles[index];document.querySelector('#townPlace span').textContent=(life.actors.get(npc.lifeId)?.place||places[index][0])+' · '+(life.actors.get(npc.lifeId)?.action||'休息');positionCamera();sayToResident(index,'今天也很高兴见到你！');window.dispatchEvent(new CustomEvent('town-npc-select',{detail:{index}}));
  }
  function focusPet(){if(!pet.visible)return;if(focusedResident===-1)savedFocusCamera={yaw,pitch,distance,target:target.clone()};focusedResident=-2;target.copy(pet.position).add(new THREE.Vector3(1.05,.25,0));yaw=.15;pitch=.68;distance=5.4;returnButton.hidden=false;host.dataset.resident='main';speech.hidden=true;document.querySelector('#townPlace b').textContent='我的鼠鼠';document.querySelector('#townPlace span').textContent='你正在陪伴的桌面伙伴';positionCamera();window.dispatchEvent(new CustomEvent('town-main-select'))}
  function focusPup(id){const item=pups.get(id);if(!item?.rig.visible)return;if(focusedResident===-1)savedFocusCamera={yaw,pitch,distance,target:target.clone()};focusedResident=-3;focusedPup=id;speech.hidden=true;target.copy(item.rig.position).add(new THREE.Vector3(1.05,.25,0));yaw=.15;pitch=.68;distance=5.4;positionCamera();returnButton.hidden=false;window.dispatchEvent(new CustomEvent("town-pup-select",{detail:{id}}))}
  function clearFocus(restore=true){if(focusedResident===-1)return;focusedResident=-1;focusedPup=null;speech.hidden=true;delete host.dataset.resident;document.querySelector('#townPlace b').textContent=activePlace||'中心广场';document.querySelector('#townPlace span').textContent=activePlace?'正在查看这里的鼠鼠和设施':'鼠鼠们碰面和交换消息的地方';if(restore&&savedFocusCamera){yaw=savedFocusCamera.yaw;pitch=savedFocusCamera.pitch;distance=savedFocusCamera.distance;target.copy(savedFocusCamera.target);positionCamera()}savedFocusCamera=null;if(!activePlace)returnButton.hidden=true}
  function sayToResident(index,text){if(index!==focusedResident)focusResident(index);speech.textContent=text||'吱吱，欢迎来找我聊天。';speech.hidden=false;clearTimeout(speech._timer);speech._timer=setTimeout(()=>{speech.hidden=true},4200)}
  function returnToTown(){if(firstPerson){stopFirstPerson();window.dispatchEvent(new CustomEvent('town-view-close'));return}if(activePlace)leavePlace();else clearFocus();window.dispatchEvent(new CustomEvent('town-view-close'))}returnButton.onclick=returnToTown;
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&activePlace&&document.body.dataset.currentPanel==='town'){e.preventDefault();e.stopImmediatePropagation();returnToTown()}},true);
  new MutationObserver(()=>{if(document.body.dataset.currentPanel!=='town'){stopFirstPerson();leavePlace()}}).observe(document.body,{attributes:true,attributeFilter:['data-current-panel']});
  function positionCamera(){camera.position.set(Math.sin(yaw)*Math.cos(pitch)*distance,Math.sin(pitch)*distance,Math.cos(yaw)*Math.cos(pitch)*distance);camera.position.add(target);camera.lookAt(target);camera.updateMatrixWorld()}positionCamera();
  host.addEventListener('pointermove',e=>{const rect=host.getBoundingClientRect();hoverPointer={x:(e.clientX-rect.left)*host.clientWidth/rect.width,y:(e.clientY-rect.top)*host.clientHeight/rect.height}});host.addEventListener('pointerleave',()=>{hoverPointer=null;hoveredActor=null});
  const playerTools=document.createElement('div');playerTools.className='town-player-tools';playerTools.hidden=true;playerTools.innerHTML='<button type="button" data-player-enter>进入鼠鼠第一视角</button><span>WASD / 方向键移动 · 鼠标环顾 · E 互动 · 空格跳跃 · Shift 跑步 · Esc 返回上帝视角</span><button type="button" data-player-exit hidden>返回上帝视角</button>';host.appendChild(playerTools);
  const playerNotice=document.createElement('p');playerNotice.className='town-player-notice';playerNotice.hidden=true;playerNotice.setAttribute('role','status');host.appendChild(playerNotice);
  function sayAsMain(text){const actor=life.actors.get('main');if(actor)actor.speech=text;playerNotice.textContent=text;playerNotice.hidden=!firstPerson;clearTimeout(playerNotice._timer);playerNotice._timer=setTimeout(()=>{playerNotice.hidden=true;if(actor?.speech===text)actor.speech=''},4500)}
  const crosshair=document.createElement('span');crosshair.className='town-player-crosshair';crosshair.hidden=true;crosshair.textContent='+';host.appendChild(crosshair);
  function startFirstPerson(){const actor=life.actors.get('main');if(!worldState.celebration||!actor||actor.frozen)return false;clearFocus();if(activePlace)leavePlace();playerSavedCamera={yaw,pitch,distance,target:target.clone()};firstPerson=true;actor.controlled=true;actor.path=[];actor.partner=null;actor.phase='controlled';actor.speech='';playerYaw=actor.heading+Math.PI;playerPitch=0;playerKeys.clear();jumpHeight=0;jumpVelocity=0;if(actor.inside)enterPlace(actor.inside);host.dataset.view='first-person';crosshair.hidden=false;playerTools.querySelector('[data-player-enter]').hidden=true;playerTools.querySelector('[data-player-exit]').hidden=false;window.dispatchEvent(new CustomEvent('town-view-close'));return true}
  function stopFirstPerson(){if(!firstPerson)return;firstPerson=false;jumpHeight=0;jumpVelocity=0;playerKeys.clear();document.exitPointerLock?.();const actor=life.actors.get('main');if(actor){actor.controlled=false;actor.phase=actor.inside?'exit-room':'idle';actor.wait=0;actor.moving=false}if(activePlace)leavePlace();if(playerSavedCamera){({yaw,pitch,distance}=playerSavedCamera);target.copy(playerSavedCamera.target)}delete host.dataset.view;crosshair.hidden=true;playerNotice.hidden=true;playerTools.querySelector('[data-player-enter]').hidden=false;playerTools.querySelector('[data-player-exit]').hidden=true;positionCamera()}
  playerTools.querySelector('[data-player-enter]').onclick=startFirstPerson;playerTools.querySelector('[data-player-exit]').onclick=stopFirstPerson;
  function updatePlayer(dt){if(!firstPerson)return;const actor=life.actors.get('main');if(!actor)return;let forward=(playerKeys.has('KeyW')||playerKeys.has('ArrowUp')?1:0)-(playerKeys.has('KeyS')||playerKeys.has('ArrowDown')?1:0),right=(playerKeys.has('KeyD')||playerKeys.has('ArrowRight')?1:0)-(playerKeys.has('KeyA')||playerKeys.has('ArrowLeft')?1:0);const speed=playerKeys.has('ShiftLeft')||playerKeys.has('ShiftRight')?1.6:.9;const norm=Math.hypot(forward,right)||1;forward/=norm;right/=norm;movePlayer(actor,(-Math.sin(playerYaw)*forward+Math.cos(playerYaw)*right)*dt*speed,(-Math.cos(playerYaw)*forward-Math.sin(playerYaw)*right)*dt*speed);actor.heading=playerYaw+Math.PI;if(jumpHeight>0||jumpVelocity>0){jumpVelocity-=dt*4;jumpHeight=Math.max(0,jumpHeight+jumpVelocity*dt);if(jumpHeight===0)jumpVelocity=0}camera.position.set(actor.position.x,.53+jumpHeight,actor.position.z);camera.rotation.order='YXZ';camera.rotation.set(playerPitch,playerYaw,0);camera.updateMatrixWorld()}
  function playerInteract(){if(!firstPerson)return;const actor=life.actors.get('main');if(!actor)return;
    if(actor.inside){if(Math.hypot(actor.position.x,actor.position.z-2.6)<.75){const old=actor.inside;leavePlace();const place=places.find(p=>p[0]===old);actor.inside=null;actor.position=entrance(old);playerYaw=facing(old);return}const nearby=roomLabels.map(l=>({...l,d:Math.hypot(l.point.x-actor.position.x,l.point.z-actor.position.z)})).sort((a,b)=>a.d-b.d)[0];if(nearby?.d<1.2){const text=nearby.button.textContent,action=text.startsWith('水壶')?'water':text.startsWith('粮仓')?'supply':text==='诊疗床'?'treat':text.includes('床')?'rest':text==='食盆'?'eat':'inspect';window.dispatchEvent(new CustomEvent('town-player-action',{detail:{action,text,place:actor.inside}}));actor.speech='看看'+text.split(' · ')[0];return}}
    const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2(0,0),camera);const hit=ray.intersectObjects(clickable,true).find(h=>{if(h.distance>2.1)return false;for(let n=h.object;n;n=n.parent)if(!n.visible)return false;return true});if(hit){let node=hit.object;while(node&&!node.userData.townAction&&!node.userData.roomAction&&!Number.isInteger(node.userData.npcIndex)&&!node.userData.pupId&&!node.userData.place)node=node.parent;if(Number.isInteger(node?.userData.npcIndex)){window.dispatchEvent(new CustomEvent('town-player-action',{detail:{action:'social',index:node.userData.npcIndex}}));return}if(node?.userData.pupId){window.dispatchEvent(new CustomEvent('town-pup-select',{detail:{id:node.userData.pupId}}));return}if(node?.userData.townAction){window.dispatchEvent(new CustomEvent('town-plaza-action',{detail:{action:node.userData.townAction}}));return}if(node?.userData.place&&!indoorNames.includes(node.userData.place)){const place=node.userData.place;window.dispatchEvent(new CustomEvent('town-player-action',{detail:{action:place==='小菜园'?'harvest':place==='跑轮公园'?'exercise':'inspect',text:place,place}}));return}}
    const nearest=places.map(p=>({p,d:Math.hypot(actor.position.x-entrance(p[0]).x,actor.position.z-entrance(p[0]).z)})).sort((a,b)=>a.d-b.d)[0];if(nearest?.d<1.15){const name=nearest.p[0];if(indoorNames.includes(name)){actor.inside=name;actor.position={x:0,z:2.6};enterPlace(name)}else{window.dispatchEvent(new CustomEvent('town-player-action',{detail:{action:name==='小菜园'?'harvest':name==='跑轮公园'?'exercise':'inspect',text:name,place:name}}))}return}sayAsMain('再靠近一点，就可以互动啦。');
  }
  document.addEventListener('keydown',e=>{if(!firstPerson||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.code==='Escape'){e.preventDefault();e.stopImmediatePropagation();stopFirstPerson();return}if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyE','Space','ShiftLeft','ShiftRight'].includes(e.code)){e.preventDefault();e.stopImmediatePropagation();if(e.code==='KeyE'){if(!e.repeat)playerInteract()}else if(e.code==='Space'){if(!e.repeat&&jumpHeight===0)jumpVelocity=1.7}else playerKeys.add(e.code)}},true);
  document.addEventListener('keyup',e=>playerKeys.delete(e.code));window.addEventListener('blur',()=>{playerKeys.clear();document.exitPointerLock?.()});
  document.addEventListener('mousemove',e=>{if(firstPerson&&document.pointerLockElement===canvas){playerYaw-=e.movementX*.003;playerPitch=Math.max(-1.3,Math.min(1.3,playerPitch-e.movementY*.003))}});
  canvas.addEventListener('contextmenu',e=>e.preventDefault());
  canvas.addEventListener('pointerdown',e=>{if(firstPerson){if(document.pointerLockElement===canvas)playerInteract();else canvas.requestPointerLock?.();return}drag={x:e.clientX,y:e.clientY,yaw,pitch,target:target.clone(),button:e.button,moved:false};canvas.setPointerCapture(e.pointerId)});
  canvas.addEventListener('pointermove',e=>{if(firstPerson){if(e.buttons===1&&document.pointerLockElement!==canvas){playerYaw-=e.movementX*.003;playerPitch=Math.max(-1.3,Math.min(1.3,playerPitch-e.movementY*.003))}return}if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(dx,dy)>4)drag.moved=true;if(drag.button===2||e.shiftKey){const right=new THREE.Vector3().setFromMatrixColumn(camera.matrix,0),forward=new THREE.Vector3().crossVectors(right,camera.up);target.copy(drag.target).addScaledVector(right,-dx*distance*.0015).addScaledVector(forward,dy*distance*.0015)}else{yaw=drag.yaw-dx*.008;pitch=Math.max(.34,Math.min(1.18,drag.pitch+dy*.006))}positionCamera()});
  canvas.addEventListener('pointerup',e=>{if(firstPerson)return;if(drag&&!drag.moved){const rect=canvas.getBoundingClientRect(),mouse=new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-((e.clientY-rect.top)/rect.height)*2+1),ray=new THREE.Raycaster();ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(clickable,true).find(hit=>{for(let node=hit.object;node;node=node.parent)if(!node.visible)return false;return true});if(hit){let object=hit.object;while(object&&!Number.isInteger(object.userData.npcIndex)&&!object.userData.mainPet&&!object.userData.pupId&&!object.userData.roomAction&&!object.userData.townAction&&!object.userData.place)object=object.parent;if(object?.userData.townAction)window.dispatchEvent(new CustomEvent('town-plaza-action',{detail:{action:object.userData.townAction}}));else if(object?.userData.roomAction)window.dispatchEvent(new CustomEvent("town-object-action",{detail:{action:object.userData.roomAction}}));else if(object?.userData.pupId)focusPup(object.userData.pupId);else if(object?.userData.mainPet)focusPet();else if(Number.isInteger(object?.userData.npcIndex))focusResident(object.userData.npcIndex);else if(!activePlace&&object?.userData.place)enterPlace(object.userData.place)}}drag=null});
  canvas.addEventListener('wheel',e=>{e.preventDefault();if(firstPerson)return;distance=Math.max(activePlace?5:14,Math.min(activePlace?20:38,distance+e.deltaY*.015));positionCamera()},{passive:false});
  function resize(){const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(host);resize();
  function placeLabel(button,point,occupied,hidden=false,anchored=false){const p=point.clone().project(camera);let x=(p.x+1)*host.clientWidth/2,y=(-p.y+1)*host.clientHeight/2;button.hidden=hidden||p.z>1;if(button.hidden){button.style.left=x+'px';button.style.top=y+'px';return}for(let tries=0;!anchored&&tries<5&&occupied.some(o=>Math.abs(o.x-x)<82&&Math.abs(o.y-y)<28);tries++)y+=24;occupied.push({x,y});button.style.left=x+'px';button.style.top=y+'px'}
  function layoutSpeech(){
    const tags=[mainTag,...residents.map(n=>n.tag),...[...pups.values()].map(p=>p.tag),...labels.map(l=>l.button),...roomLabels.map(l=>l.button)];
    const bounds=el=>({left:el.offsetLeft-el.offsetWidth/2,right:el.offsetLeft+el.offsetWidth/2,top:el.offsetTop-el.offsetHeight,bottom:el.offsetTop});
    const occupied=tags.filter(tag=>!tag.hidden).map(bounds);
    function above(bubble,tag){
      if(bubble.hidden)return;if(!tag){bubble.hidden=true;return}
      const anchor=tag.hidden?{top:parseFloat(tag.style.top)-20}:bounds(tag),width=bubble.offsetWidth,height=bubble.offsetHeight;
      const x=Math.max(width/2+6,Math.min(host.clientWidth-width/2-6,parseFloat(tag.style.left)));let bottom=anchor.top-8;
      for(let i=0;i<=occupied.length;i++){const hits=occupied.filter(r=>x+width/2>r.left-6&&x-width/2<r.right+6&&bottom>r.top-6&&bottom-height<r.bottom+6);if(!hits.length)break;bottom=Math.min(...hits.map(r=>r.top))-8}
      bubble.style.left=x+'px';bubble.style.top=bottom+'px';occupied.push({left:x-width/2,right:x+width/2,top:bottom-height,bottom});
    }
    above(lifeBubbles.get('main')||{hidden:true},mainTag);
    residents.forEach(n=>above(lifeBubbles.get(n.lifeId)||{hidden:true},n.tag));
    pups.forEach(p=>above(lifeBubbles.get(p.data.id)||{hidden:true},p.tag));
    if(focusedResident>=0)above(speech,residents[focusedResident].tag);
  }
  function syncPups(){const list=worldState.offspring||[],ids=new Set(list.map(p=>p.id));for(const [id,item] of pups){if(!ids.has(id)){life.remove(id);scene.remove(item.rig);const hitIndex=clickable.indexOf(item.rig);if(hitIndex>=0)clickable.splice(hitIndex,1);if(focusedPup===id)clearFocus();item.tag.remove();pups.delete(id)}}list.forEach((data,index)=>{let item=pups.get(data.id);if(!item){const rig=hamster(),tag=document.createElement('button');tag.type='button';tag.className='town-label town-npc-label town-pup-label';tag.hidden=true;tag.dataset.pupId=data.id;tag.onclick=()=>focusPup(data.id);rig.userData.pupId=data.id;clickable.push(rig);host.appendChild(tag);scene.add(rig);item={rig,tag};pups.set(data.id,item)}item.data=data;item.index=index;item.rig.scale.setScalar(window.TownSimulation.growthScale(data.ageYears));item.rig.visible=!indoorNames.includes(activePlace)||activePlace==='鼠鼠小屋';item.tag.textContent=`${data.name} · ${data.stage}`;item.tag.title=`${(data.parents||['鼠鼠',data.parent]).filter(Boolean).join('与')}的孩子`;})}
  const clock=new THREE.Clock();let previousTime=0;
  function draw(){requestAnimationFrame(draw);const t=clock.getElapsedTime(),dt=Math.min(.1,t-previousTime);previousTime=t;if(document.body.dataset.currentPanel!=='town')return;
    placeModels.get('跑轮公园').userData.setRunning(dt,[...life.actors.values()].some(a=>a.place==='跑轮公园'&&a.phase==='activity'&&a.action==='跑轮'));life.tick(dt,worldState.part==='白天');updatePlayer(dt);const focusedId=focusedResident===-2?'main':focusedResident===-3?focusedPup:focusedResident>=0?residents[focusedResident].lifeId:null,focusedActor=life.actors.get(focusedId);if(focusedActor&&((indoorNames.includes(activePlace)&&focusedActor.inside!==activePlace)||(!indoorNames.includes(activePlace)&&focusedActor.inside))){clearFocus();window.dispatchEvent(new CustomEvent('town-view-close'))}const occupied=[];let candidate=null;if(hoverPointer&&!drag){let nearest=32;for(const [id,rig] of [['main',pet],...residents.map(n=>[n.lifeId,n.rig]),...[...pups.values()].map(p=>[p.data.id,p.rig])]){if(!rig.visible)continue;const p=rig.position.clone().add(new THREE.Vector3(0,.4*rig.scale.x,0)).project(camera),d=Math.hypot((p.x+1)*host.clientWidth/2-hoverPointer.x,(-p.y+1)*host.clientHeight/2-hoverPointer.y);if(id===hoveredActor&&d<48){candidate=id;break}if(d<nearest){nearest=d;candidate=id}}}if(candidate){hoveredActor=candidate;hoverUntil=t+.3}else if(t>hoverUntil||!hoverPointer||drag)hoveredActor=null;renderActor(pet,life.actors.get('main'),t);const main=life.actors.get('main');mainTag.textContent='鼠鼠';placeLabel(mainTag,pet.position.clone().add(new THREE.Vector3(0,.8,0)),occupied,firstPerson||!pet.visible||(focusedResident!==-1&&focusedResident!==-2),true);
    if(main)document.querySelector('#townActivity').textContent='鼠鼠'+(main.phase==='moving'?'正在前往'+main.destination:'正在'+main.place+main.action)+'。';
    weatherFx.rotation.y=t*.025;if(weatherFx.children[0])weatherFx.children[0].position.y=-(t*2)%4;
    labels.forEach(({button,point})=>placeLabel(button,point,occupied,firstPerson||!!activePlace||focusedResident!==-1));
    residents.forEach((npc,index)=>{const actor=life.actors.get(npc.lifeId);renderActor(npc.rig,actor,t);npc.tag.textContent=(worldState.npcs?.[index]?.name||roles[index])+' '+(worldState.npcs?.[index]?.sex==='male'?'♂':'♀');placeLabel(npc.tag,npc.rig.position.clone().add(new THREE.Vector3(0,.8,0)),occupied,!npc.rig.visible||(focusedResident!==-1?focusedResident!==index:hoveredActor!==npc.lifeId),true)});
    pups.forEach(item=>{renderActor(item.rig,life.actors.get(item.data.id),t);placeLabel(item.tag,item.rig.position.clone().add(new THREE.Vector3(0,.75*item.rig.scale.x,0)),occupied,!item.rig.visible||(focusedResident!==-1?focusedPup!==item.data.id:hoveredActor!==item.data.id),true)});
    roomLabels.forEach(({button,point})=>placeLabel(button,point,occupied,false));
    layoutSpeech();
    if(firstPerson)pet.visible=false;renderer.render(scene,camera);
  }draw();
  function applyWorld(next={}){
    const oldBoard=worldState.schoolBoard;worldState=next;if(activePlace==='鼠鼠学校'&&oldBoard!==next.schoolBoard)buildRoom(activePlace);if(firstPerson&&!next.celebration)stopFirstPerson();playerTools.hidden=!next.celebration;const night=['夜晚','深夜'].includes(next.part),dusk=next.part==='傍晚',lampsOn=night||dusk,sky=new THREE.Color(next.weather?.sky||0xcbd7a9);if(night)sky.multiplyScalar(.22);else if(dusk)sky.multiplyScalar(.55);scene.background.copy(sky);scene.fog.color.copy(sky);ambient.intensity=(night?.65:dusk?1.1:2.4)*(next.weather?.light||1);sun.intensity=(night?.38:dusk?1.15:3.1)*(next.weather?.light||1);sun.color.set(night?0x7995c2:dusk?0xffb66f:0xffe4bd);lampBulbs.forEach(({material,light,pool})=>{material.emissiveIntensity=lampsOn?(night?1.8:1.6):0;light.intensity=lampsOn?(night?7:7):0;pool.material.opacity=lampsOn?(night?.035:.07):0});document.body.dataset.townPart=next.part||'';
    syncPups();syncLife();life.setResting(next.sleepRequested);life.setCelebration(next.celebration||null);placeModels.get('中心广场').userData.setEvent(next.celebration);placeModels.get('小菜园').userData.setGrowth(next.gardenProgress??.5);pet.scale.setScalar(window.TownSimulation.growthScale(next.ageYears??.7));pet.visible=next.alive!==false||next.pendingFarewell?.phase!=='buried';residents.forEach((resident,i)=>{const data=next.npcs?.[i],inside=indoorNames.includes(activePlace);resident.rig.visible=data?.alive!==false&&(!inside||places[i][0]===activePlace);resident.tag.textContent=data?`${data.name} ${data.sex==='male'?'♂':'♀'}`:roles[i]});
    while(weatherFx.children.length){const child=weatherFx.children[0];child.geometry.dispose();child.material.dispose();weatherFx.remove(child)}
    if(next.weather?.name==='小雨'){const points=[];for(let i=0;i<260;i++)points.push((Math.random()-.5)*25,Math.random()*12,(Math.random()-.5)*25);const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(points,3));weatherFx.add(new THREE.Points(geometry,new THREE.PointsMaterial({color:0xd8edf0,size:.055,transparent:true,opacity:.72})))}
    placeModels.get('墓地').userData.setMemorials(next.memorials||[]);
    const location=places.find(p=>p[0]===next.place);if(location&&!activePlace){pet.userData.home={x:location[1]+.7,z:location[2]+1.3}}
    if(activePlace==='鼠鼠小屋'){buildRoom(activePlace)}
  }
  window.TownApp={sayAsMain,startFirstPerson,stopFirstPerson,playerInteract,resize,enterPlace,leavePlace,returnToTown,focusPup,focusResident,focusPet,clearFocus,sayToResident,applyWorld,inspect:()=>({life:life.inspect(),firstPerson,playerCamera:{yaw:playerYaw,pitch:playerPitch,jumpHeight},cemeteryView:activePlace==='墓地',cemeteryMemorialNames:placeModels.get('墓地').userData.memorialNames,townRadius:18,cottageModel:true,plazaArea:placeModels.get('中心广场').userData.footprint,gardenArea:placeModels.get('小菜园').userData.footprint,celebration:worldState.celebration||null,cakeVisible:placeModels.get('中心广场').userData.cake.visible,birthdayHats:[['main',pet],...residents.map(n=>[n.lifeId,n.rig]),...[...pups.values()].map(p=>[p.data.id,p.rig])].filter(([id,rig])=>rig.userData.birthdayHat?.visible).map(([id])=>id),pups:[...pups.values()].map(p=>({id:p.data.id,scale:p.rig.scale.x,visible:p.rig.visible,loaded:!!p.rig.userData.loaded})),activePlace,focusedResident,focusedPup,interiorVisible:room.visible,petVisible:pet.visible,visibleResidentCount:residents.filter(n=>n.rig.visible).length,streetLampCount:lampBulbs.length,litStreetLampCount:lampBulbs.filter(item=>item.light.intensity>0).length,lampPositions,furniture:roomLabels.map(x=>x.button.textContent),camera:{yaw,pitch,distance,target:target.toArray()},npcCount:residents.filter(n=>n.rig.userData.loaded).length,petLoaded:!!pet.userData.loaded,jointCount:pet.userData.joints?.length||0,gaitBoneCount:Object.keys(pet.userData.bones||{}).filter(name=>/Arm|Leg|Hand|Foot|Spine|Neck|Head/.test(name)).length,armTucked:pet.userData.armTucked,forepawSpan:pet.userData.forepawSpan,gaitSample:pet.userData.gaitSample,petHeight:new THREE.Box3().setFromObject(pet).getSize(new THREE.Vector3()).y,positions:residents.map(n=>n.rig.position.toArray())})};
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
